package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

// DefaultConfigPath returns the canonical location for config.yaml,
// regardless of whether the file exists yet. Used by `im-gateway init`
// and `im-gateway start` (when no path is given on the command line).
func DefaultConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home dir: %w", err)
	}
	return filepath.Join(home, ".vetta", "im-gateway", "config.yaml"), nil
}

// GenerateTemplate writes a starter config.yaml + an empty credentials.yaml
// stub at the gateway's standard locations. The template is intentionally
// verbose with comments so users can edit it directly without consulting
// docs.
//
// Behavior:
//   - If config.yaml already exists, returns ErrAlreadyInitialized (caller
//     decides whether to overwrite). Never overwrites silently.
//   - credentials.yaml is created with chmod 0600 and only the keys
//     scaffolded — no actual secret values written.
//   - The directory is created with chmod 0700 if missing.
func GenerateTemplate() (configPath, credentialsPath string, err error) {
	configPath, err = DefaultConfigPath()
	if err != nil {
		return "", "", err
	}
	dir := filepath.Dir(configPath)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", "", fmt.Errorf("create config dir: %w", err)
	}

	if _, statErr := os.Stat(configPath); statErr == nil {
		return configPath, "", ErrAlreadyInitialized
	} else if !errors.Is(statErr, os.ErrNotExist) {
		return "", "", fmt.Errorf("stat %s: %w", configPath, statErr)
	}

	if err := os.WriteFile(configPath, []byte(configTemplate), 0o644); err != nil {
		return "", "", fmt.Errorf("write %s: %w", configPath, err)
	}

	credentialsPath = filepath.Join(dir, credentialsFilename)
	if _, statErr := os.Stat(credentialsPath); errors.Is(statErr, os.ErrNotExist) {
		if err := os.WriteFile(credentialsPath, []byte(credentialsTemplate), 0o600); err != nil {
			return configPath, "", fmt.Errorf("write %s: %w", credentialsPath, err)
		}
	}
	return configPath, credentialsPath, nil
}

// ErrAlreadyInitialized signals that GenerateTemplate found an existing
// config.yaml. The caller (e.g. `im-gateway init`) should refuse to
// overwrite without explicit user confirmation.
var ErrAlreadyInitialized = errors.New("config: already initialized")

const configTemplate = `# vetta im-gateway configuration
# Generated by ` + "`im-gateway init`" + `. Edit freely; missing fields fall back to defaults.
# See: apps/im-gateway/README.md and openspec/changes/add-im-gateway-feishu/

# Which IM transport to run.
# One of: mock, feishu, wechat, telegram, slack, discord, signal, whatsapp, imessage
transport:
  name: mock
  # feishu:
  #   baseUrl: https://open.feishu.cn  # optional override
  # telegram:
  #   allowedUserIds: []               # numeric user IDs; empty = accept all DMs
  # slack:
  #   allowedUserIds: []
  #   allowedChannelIds: []            # channel IDs, not names
  # discord:
  #   allowedUserIds: []
  #   allowedGuildIds: []
  # signal:
  #   endpoint: http://127.0.0.1:8080  # signal-cli daemon --http address
  #   account: "+8613800000000"        # E.164 number the daemon serves
  #   allowedNumbers: []
  #   attachmentsDir: ""               # signal-cli attachment cache, enables inbound media
  # whatsapp:
  #   allowedNumbers: []               # E.164; session db lives at paths.whatsappState
  # imessage:
  #   dbPath: ""                       # default ~/Library/Messages/chat.db (macOS only)
  #   allowedHandles: []

hostClient:
  # Path to the coding-agent binary. Empty = search $PATH for "vetta".
  codingAgentBin: ""
  # Maximum number of concurrent coding-agent subprocesses. Default 8.
  poolMaxSize: 8
  # How long OpenSession waits for the subprocess's first JSON line.
  # The first session after a desktop app launch/update pays an Electron
  # cold start (~10s), so keep this well above the warm-start latency.
  handshakeTimeout: 30s
  # How long Close() waits for graceful exit before SIGKILL.
  closeTimeout: 5s

logging:
  level: info       # debug | info | warn | error
  file: ""          # empty = stderr only

# Override on-disk file locations. All optional.
# paths:
#   conversationCwd: ~/.vetta/im-gateway/conversation
#   state: ~/.vetta/im-gateway/state.json
#   logsDir: ~/.vetta/im-gateway/logs
`

const credentialsTemplate = `# vetta im-gateway credentials
# Permissions MUST be 0600. ` + "`im-gateway init`" + ` sets that automatically.
#
# Preferred storage is the OS keychain (macOS Keychain / linux Secret Service /
# Windows Credential Manager). This file is the fallback for headless or CI
# environments. You can also set values via environment variables:
#
#   IM_GATEWAY_FEISHU_APP_ID
#   IM_GATEWAY_FEISHU_APP_SECRET
#   IM_GATEWAY_TELEGRAM_BOT_TOKEN
#   IM_GATEWAY_SLACK_BOT_TOKEN
#   IM_GATEWAY_SLACK_APP_TOKEN
#   IM_GATEWAY_DISCORD_BOT_TOKEN
#
# Sources are merged in this order (later overrides earlier):
#   keychain → credentials.yaml → environment
#
# signal / whatsapp / imessage have no static secrets: signal credentials
# are owned by your signal-cli daemon, whatsapp pairs via QR into the
# sidecar-owned session db, and imessage uses macOS permissions.

feishu:
  appId: ""
  appSecret: ""
telegram:
  botToken: ""
slack:
  botToken: ""   # xoxb-…
  appToken: ""   # xapp-…
discord:
  botToken: ""
`
