import type { AgentSession } from "../core/agent-session.js";
import type { CreateAgentSessionOptions, CreateAgentSessionResult } from "../core/sdk.js";

export type SdkCompatibilityDisposition =
	| "greenfield-core"
	| "runtime-capability"
	| "product-adapter"
	| "legacy-concrete";

/**
 * createAgentSession 的迁移清单。`satisfies Record` 让新增或删除 option 必须显式更新分类。
 */
export const SDK_CREATE_OPTION_COMPATIBILITY = {
	cwd: "greenfield-core",
	agentDir: "greenfield-core",
	authStorage: "product-adapter",
	modelRegistry: "product-adapter",
	model: "greenfield-core",
	thinkingLevel: "greenfield-core",
	scopedModels: "runtime-capability",
	tools: "product-adapter",
	scenario: "greenfield-core",
	agentMode: "runtime-capability",
	customTools: "product-adapter",
	additionalHookAdapterFactories: "product-adapter",
	resourceLoader: "legacy-concrete",
	sessionManager: "legacy-concrete",
	settingsManager: "legacy-concrete",
	appendSystemPrompt: "product-adapter",
	includeAgentSkills: "product-adapter",
	env: "greenfield-core",
	memoryMode: "product-adapter",
	memoryFile: "product-adapter",
	memoryCharLimit: "product-adapter",
	askUserQuestion: "runtime-capability",
	enableBackgroundTasks: "product-adapter",
	enableSubagents: "product-adapter",
	subagentTypeRegistry: "product-adapter",
	subagentSessionFactory: "legacy-concrete",
	subagentMaxConcurrent: "product-adapter",
	enableMcp: "product-adapter",
	serverUrl: "product-adapter",
	tracer: "runtime-capability",
	tracingTraceName: "runtime-capability",
	tracingMetadata: "runtime-capability",
	agentPlugins: "product-adapter",
	invokePluginTool: "product-adapter",
	invokePluginContinuation: "product-adapter",
	invokePluginSystemPrompt: "product-adapter",
} as const satisfies Record<keyof CreateAgentSessionOptions, SdkCompatibilityDisposition>;

/** createAgentSession 返回值的兼容责任，避免切换工厂时遗漏非 Session 字段。 */
export const SDK_CREATE_RESULT_COMPATIBILITY = {
	session: "greenfield-core",
	extensionsResult: "product-adapter",
	modelFallbackMessage: "product-adapter",
} as const satisfies Record<keyof CreateAgentSessionResult, SdkCompatibilityDisposition>;

/**
 * 现有 AgentSession 的完整公开成员清单。
 *
 * greenfield-core 已进入第 210 阶段门面；runtime-capability 已有中立 Port 但尚未全部
 * 暴露；product-adapter 需要产品层组合；legacy-concrete 是不能下沉进 Runtime 的旧实现泄漏。
 */
export const SDK_SESSION_MEMBER_COMPATIBILITY = {
	agent: "legacy-concrete",
	sessionManager: "legacy-concrete",
	settingsManager: "legacy-concrete",
	modelRegistry: "product-adapter",
	subagents: "product-adapter",
	listSubagents: "runtime-capability",
	interruptSubagent: "runtime-capability",
	clearFinishedSubagents: "runtime-capability",
	mcpManager: "legacy-concrete",
	subscribe: "greenfield-core",
	dispose: "greenfield-core",
	close: "greenfield-core",
	state: "greenfield-core",
	model: "greenfield-core",
	thinkingLevel: "greenfield-core",
	isStreaming: "greenfield-core",
	systemPrompt: "product-adapter",
	retryAttempt: "runtime-capability",
	getActiveToolNames: "runtime-capability",
	getAllTools: "product-adapter",
	setActiveToolsByName: "runtime-capability",
	reconfigureCustomTools: "product-adapter",
	reconfigureAgentPlugins: "product-adapter",
	agentMode: "runtime-capability",
	setAgentMode: "runtime-capability",
	prepareSystemPromptForAgentRun: "product-adapter",
	isCompacting: "runtime-capability",
	messages: "greenfield-core",
	steeringMode: "runtime-capability",
	followUpMode: "runtime-capability",
	sessionFile: "greenfield-core",
	sessionId: "greenfield-core",
	sessionName: "runtime-capability",
	getSessionBranch: "runtime-capability",
	scopedModels: "runtime-capability",
	setScopedModels: "runtime-capability",
	promptTemplates: "product-adapter",
	todoStore: "legacy-concrete",
	backgroundTasks: "product-adapter",
	memoryMode: "product-adapter",
	memoryFile: "product-adapter",
	memoryCharLimit: "product-adapter",
	prompt: "greenfield-core",
	steer: "greenfield-core",
	followUp: "greenfield-core",
	sendCustomMessage: "runtime-capability",
	sendUserMessage: "runtime-capability",
	clearQueue: "runtime-capability",
	pendingMessageCount: "runtime-capability",
	getSteeringMessages: "runtime-capability",
	getFollowUpMessages: "runtime-capability",
	resourceLoader: "legacy-concrete",
	abort: "greenfield-core",
	newSession: "runtime-capability",
	setModel: "greenfield-core",
	cycleModel: "runtime-capability",
	setThinkingLevel: "greenfield-core",
	cycleThinkingLevel: "runtime-capability",
	getAvailableThinkingLevels: "runtime-capability",
	supportsXhighThinking: "runtime-capability",
	supportsThinking: "runtime-capability",
	setSteeringMode: "runtime-capability",
	setFollowUpMode: "runtime-capability",
	compact: "runtime-capability",
	abortCompaction: "runtime-capability",
	abortBranchSummary: "runtime-capability",
	flushMemory: "product-adapter",
	preCallCompaction: "product-adapter",
	setAutoCompactionEnabled: "runtime-capability",
	autoCompactionEnabled: "runtime-capability",
	bindExtensions: "product-adapter",
	reloadMcp: "product-adapter",
	reload: "product-adapter",
	abortRetry: "runtime-capability",
	isRetrying: "runtime-capability",
	autoRetryEnabled: "runtime-capability",
	setAutoRetryEnabled: "runtime-capability",
	executeBash: "runtime-capability",
	recordBashResult: "legacy-concrete",
	abortBash: "runtime-capability",
	isBashRunning: "runtime-capability",
	hasPendingBashMessages: "runtime-capability",
	switchSession: "runtime-capability",
	setSessionName: "runtime-capability",
	fork: "runtime-capability",
	navigateTree: "runtime-capability",
	switchBranch: "runtime-capability",
	appendBranchSummary: "runtime-capability",
	deleteMessage: "runtime-capability",
	replaceLastUserMessage: "runtime-capability",
	exportForkToNewFile: "runtime-capability",
	getUserMessagesForForking: "runtime-capability",
	getSessionStats: "runtime-capability",
	getContextUsage: "runtime-capability",
	exportToHtml: "product-adapter",
	getLastAssistantText: "runtime-capability",
	hasExtensionHandlers: "product-adapter",
	extensionRunner: "legacy-concrete",
} as const satisfies Record<keyof AgentSession, SdkCompatibilityDisposition>;
