export const PLUGIN_MANAGEMENT_CHANNELS = {
	LIST: "vetta:plugins:list",
	LIST_ALL: "vetta:plugins:list-all",
	INSTALL_FROM_ARCHIVE: "vetta:plugins:install-from-archive",
	INSTALL_FROM_URL: "vetta:plugins:install-from-url",
	INSTALL_FROM_PATH: "vetta:plugins:install-from-path",
	REGISTER_MODE_GATE: "vetta:plugins:register-mode-gate",
	SET_CONTRIBUTION_MODE: "vetta:plugins:set-contribution-mode",
	UNINSTALL: "vetta:plugins:uninstall",
	SET_ENABLED: "vetta:plugins:set-enabled",
	GRANT_PERMISSIONS: "vetta:plugins:grant-permissions",
	REVOKE_PERMISSIONS: "vetta:plugins:revoke-permissions",
	GRANT_COMMANDS: "vetta:plugins:grant-commands",
	REVOKE_COMMANDS: "vetta:plugins:revoke-commands",
	RELOAD: "vetta:plugins:reload",
	DEV_WATCH_START: "vetta:plugins:dev-watch-start",
	DEV_WATCH_STOP: "vetta:plugins:dev-watch-stop",
} as const;

export const PLUGIN_EXECUTION_CHANNELS = {
	COMMAND_RUN: "vetta:plugins:command-run",
	COMMAND_SPAWN: "vetta:plugins:command-spawn",
	COMMAND_SPAWN_STOP: "vetta:plugins:command-spawn-stop",
	COMMAND_SPAWN_STATUS: "vetta:plugins:command-spawn-status",
	COMMAND_SPAWN_EXIT: "vetta:plugins:command-spawn-exit",
	OFFSCREEN_CAPTURE: "vetta:plugins:offscreen-capture",
	OFFSCREEN_RELEASE: "vetta:plugins:offscreen-release",
	NETWORK_REQUEST: "vetta:plugins:network:request",
	GATEWAY_REQUEST: "vetta:plugins:gateway:request",
	STORAGE_READ_JSON: "vetta:plugins:storage:read-json",
	STORAGE_WRITE_JSON: "vetta:plugins:storage:write-json",
	STORAGE_LIST: "vetta:plugins:storage:list",
	STORAGE_READ_FILE: "vetta:plugins:storage:read-file",
	STORAGE_WRITE_FILE: "vetta:plugins:storage:write-file",
	STORAGE_PUT_BLOB: "vetta:plugins:storage:put-blob",
	STORAGE_PUT_BLOB_FROM_FILE: "vetta:plugins:storage:put-blob-from-file",
	STORAGE_READ_BLOB: "vetta:plugins:storage:read-blob",
	STORAGE_GET_BLOB_REF: "vetta:plugins:storage:get-blob-ref",
} as const;

export const PLUGIN_CONTRIBUTION_CHANNELS = {
	BEGIN_LOAD: "vetta:plugins:agent-contributions-begin-load",
	COMMIT_LOAD: "vetta:plugins:agent-contributions-commit-load",
	TOOL_REGISTER: "vetta:plugins:agent-tool-register",
	TOOL_UNREGISTER: "vetta:plugins:agent-tool-unregister",
	TOOL_REQUEST: "vetta:plugins:agent-tool-request",
	TOOL_RESPONSE: "vetta:plugins:agent-tool-response",
	HOOK_REGISTER: "vetta:plugins:agent-hook-register",
	HOOK_UNREGISTER: "vetta:plugins:agent-hook-unregister",
	HOOK_REQUEST: "vetta:plugins:agent-hook-request",
	HOOK_RESPONSE: "vetta:plugins:agent-hook-response",
	HANDLER_RELEASE: "vetta:plugins:agent-handler-release",
	CLEAR: "vetta:plugins:agent-contributions-clear",
	APP_ACTION_REGISTER: "vetta:plugins:app-action-register",
	APP_ACTION_COMMIT: "vetta:plugins:app-action-activation-commit",
	APP_ACTION_ABORT: "vetta:plugins:app-action-activation-abort",
	APP_ACTION_UNREGISTER: "vetta:plugins:app-action-unregister",
	APP_ACTION_REQUEST: "vetta:plugins:app-action-request",
	APP_ACTION_CANCEL: "vetta:plugins:app-action-cancel",
	APP_ACTION_RESPONSE: "vetta:plugins:app-action-response",
	CONTINUATION_REGISTER: "vetta:plugins:continuation-register",
	CONTINUATION_UNREGISTER: "vetta:plugins:continuation-unregister",
	CONTINUATION_REQUEST: "vetta:plugins:continuation-request",
	CONTINUATION_RESPONSE: "vetta:plugins:continuation-response",
	SYSTEM_PROMPT_REGISTER: "vetta:plugins:system-prompt-provider-register",
	SYSTEM_PROMPT_UNREGISTER: "vetta:plugins:system-prompt-provider-unregister",
	SYSTEM_PROMPT_REQUEST: "vetta:plugins:system-prompt-request",
	SYSTEM_PROMPT_RESPONSE: "vetta:plugins:system-prompt-response",
	GET_SETTINGS: "vetta:plugins:get-settings",
	SET_SETTINGS: "vetta:plugins:set-settings",
	SETTINGS_CHANGED: "vetta:plugins:settings-changed",
	PLUGINS_CHANGED: "vetta:plugins:changed",
} as const;

export const PLUGIN_MEDIA_CHANNELS = {
	REGISTER: "vetta:plugins:media-provider-register",
	UNREGISTER: "vetta:plugins:media-provider-unregister",
	REQUEST: "vetta:plugins:media-provider-request",
	CHANGED: "vetta:plugins:media-providers-changed",
	RESPONSE: "vetta:plugins:media-provider-response",
	UPLOAD_INPUT: "vetta:plugins:media-provider-input-upload",
} as const;
