import { CAPABILITY_PREFIXES } from "./contracts.js";

/** Stable prefix for Vetta-owned domain capabilities. Prefixes are never authorization rules. */
export const VETTA_DOMAIN_CAPABILITY_PREFIX = CAPABILITY_PREFIXES.VETTA_DOMAIN;

export {
	type AgentExperimentalSettings,
	type AgentExperimentalSettingsUpdate,
	DOMAIN_AGENT_SETTINGS_CAPABILITIES,
	DOMAIN_AGENT_SETTINGS_CAPABILITY_CATALOG,
} from "./domain/agent-settings.js";
export {
	BATCH_COMMAND_STATUSES,
	BATCH_EXECUTION_MODES,
	BATCH_SKILL_TYPES,
	BATCH_TASK_STATUSES,
	type BatchCommandStatus,
	type BatchExecutionMode,
	type BatchProject,
	type BatchProjectCreateData,
	type BatchProjectCreateInput,
	type BatchProjectIdInput,
	type BatchProjectUpdateData,
	type BatchProjectUpdateInput,
	type BatchSkillRef,
	type BatchSkillType,
	type BatchTask,
	type BatchTaskCommandResult,
	type BatchTaskIdInput,
	type BatchTaskIdsInput,
	type BatchTaskResumeInput,
	type BatchTaskStatus,
	DOMAIN_BATCH_TASK_CAPABILITIES,
} from "./domain/batch-task.js";
export {
	DOMAIN_DOWNLOAD_CAPABILITIES,
	DOMAIN_DOWNLOAD_CAPABILITY_CATALOG,
	DOWNLOAD_STATUSES,
	type DownloadCancelInput,
	type DownloadItem,
	type DownloadStatus,
} from "./domain/download.js";
export {
	type DefaultExecutionModeSettingInput,
	DOMAIN_GENERAL_SETTINGS_CAPABILITIES,
	DOMAIN_GENERAL_SETTINGS_CAPABILITY_CATALOG,
	GENERAL_EXECUTION_MODES,
	type GeneralExecutionMode,
	type GeneralSettingsSnapshot,
	type NotificationsSettingInput,
	SANDBOX_BACKENDS,
	SANDBOX_STATUSES,
	type SandboxBackend,
	type SandboxCapabilitySnapshot,
	type SandboxFeatures,
	type SandboxStatus,
	type WorkspaceSettingInput,
} from "./domain/general-settings.js";
export {
	DOMAIN_IM_CAPABILITIES,
	IM_LOG_LEVELS,
	IM_TRANSPORT_STATUSES,
	IM_TRANSPORTS,
	type ImAgentModel,
	type ImAgentModelSettingInput,
	type ImEnabledInput,
	type ImLogEntry,
	type ImLogLevel,
	type ImLogListInput,
	type ImRuntimeStatus,
	type ImStatusSnapshot,
	type ImTransport,
	type ImTransportStatus,
} from "./domain/im.js";
export {
	DOMAIN_KNOWLEDGE_CAPABILITIES,
	KNOWLEDGE_NODE_TYPES,
	KNOWLEDGE_PROCESS_STATUSES,
	KNOWLEDGE_SCAN_REASONS,
	type KnowledgeAddFilesInput,
	type KnowledgeBase,
	type KnowledgeDeleteEntryInput,
	type KnowledgeFileStatus,
	type KnowledgeFileStatuses,
	type KnowledgeNameInput,
	type KnowledgeNode,
	type KnowledgeNodeType,
	type KnowledgeProcessingSettings,
	type KnowledgeProcessingUpdate,
	type KnowledgeProcessStatus,
	type KnowledgeRenameInput,
	type KnowledgeScanReason,
	type KnowledgeScanResult,
	type KnowledgeSetProcessingInput,
} from "./domain/knowledge.js";
export {
	DOMAIN_MCP_CAPABILITIES,
	MCP_SERVER_TYPES,
	type McpHttpServerUpsertData,
	type McpServerDetail,
	type McpServerNameInput,
	type McpServerSetEnabledInput,
	type McpServerSummary,
	type McpServerType,
	type McpServerUpsertData,
	type McpServerUpsertInput,
	type McpStdioServerUpsertData,
} from "./domain/mcp.js";
export {
	DOMAIN_MODEL_CAPABILITIES,
	type ModelConfigSnapshot,
	type ModelCost,
	type ModelDefaultInput,
	type ModelDefaultResult,
	type ModelDefinitionDetail,
	type ModelKeyValidationInput,
	type ModelListResult,
	type ModelProbeInput,
	type ModelProbeResult,
	type ModelProviderConfigSnapshot,
	type ModelProviderDetail,
	type ModelProviderInput,
	type ModelProviderSummary,
	type ModelProviderUpsertData,
	type ModelProviderUpsertInput,
	type ModelSummary,
} from "./domain/model.js";
export {
	DOMAIN_PROJECT_CAPABILITIES,
	DOMAIN_PROJECT_CAPABILITY_CATALOG,
	type ProjectCreateInput,
	type ProjectEntry,
	type ProjectListResult,
	type ProjectOpenInput,
	type ProjectPathInput,
	type ProjectRenameInput,
} from "./domain/project.js";
export {
	DOMAIN_SCHEDULER_CAPABILITIES,
	SCHEDULER_COMMAND_STATUSES,
	SCHEDULER_EXECUTION_MODES,
	SCHEDULER_LAST_RUN_STATUSES,
	SCHEDULER_RECORD_STATUSES,
	SCHEDULER_SKILL_TYPES,
	type SchedulerCommandResult,
	type SchedulerCommandStatus,
	type SchedulerExecutionMode,
	type SchedulerExecutionRecord,
	type SchedulerLastRunStatus,
	type SchedulerRecordStatus,
	type SchedulerSkillRef,
	type SchedulerSkillType,
	type SchedulerTask,
	type SchedulerTaskCreateData,
	type SchedulerTaskCreateInput,
	type SchedulerTaskIdInput,
	type SchedulerTaskSetEnabledInput,
	type SchedulerTaskUpdateData,
	type SchedulerTaskUpdateInput,
} from "./domain/scheduler.js";
export {
	DOMAIN_SESSION_CAPABILITIES,
	DOMAIN_SESSION_CAPABILITY_CATALOG,
	type SessionHistoryEntry,
	type SessionListInput,
	type SessionRuntimeProject,
} from "./domain/session.js";
export {
	DOMAIN_QUICK_PANEL_CAPABILITIES,
	DOMAIN_QUICK_PANEL_CAPABILITY_CATALOG,
	DOMAIN_SHORTCUT_CAPABILITIES,
	DOMAIN_SHORTCUT_CAPABILITY_CATALOG,
	QUICK_PANEL_POST_SEND_BEHAVIORS,
	QUICK_PANEL_TRIGGERS,
	type QuickPanelPostSendBehavior,
	type QuickPanelPostSendBehaviorInput,
	type QuickPanelSettings,
	type QuickPanelTrigger,
	type QuickPanelTriggerInput,
	type ShortcutActionInput,
	type ShortcutBinding,
	type ShortcutBindingInput,
	type ShortcutBindingResetResult,
	type ShortcutBindingsResult,
	type ShortcutSettings,
} from "./domain/shortcut.js";
export {
	DOMAIN_SKILL_CAPABILITIES,
	DOMAIN_SKILL_CAPABILITY_CATALOG,
	INSTALLED_SKILL_SOURCES,
	type InstalledSkill,
	type InstalledSkillSource,
	SKILL_TYPES,
	type SkillInfo,
	type SkillListInput,
	type SkillSetEnabledInput,
	type SkillSetEnabledResult,
	type SkillType,
	type SkillUninstallInput,
} from "./domain/skill.js";
export {
	DOMAIN_UPDATER_CAPABILITIES,
	DOMAIN_UPDATER_CAPABILITY_CATALOG,
	UPDATER_PHASES,
	type UpdaterPhase,
	type UpdaterState,
} from "./domain/updater.js";
export {
	DOMAIN_WEBHOOK_CAPABILITIES,
	WEBHOOK_KINDS,
	WEBHOOK_MESSAGE_LEVELS,
	type WebhookCreateData,
	type WebhookCreateInput,
	type WebhookDingtalkOptions,
	type WebhookEndpoint,
	type WebhookFeishuOptions,
	type WebhookIdInput,
	type WebhookKind,
	type WebhookMessage,
	type WebhookMessageLevel,
	type WebhookProviderDescriptor,
	type WebhookSendInput,
	type WebhookSendResult,
	type WebhookSetEnabledInput,
	type WebhookUpdateData,
	type WebhookUpdateInput,
} from "./domain/webhook.js";
