export {
	addSessionGrant,
	assertSandboxPathNotDenied,
	clearSessionGrants,
	collectShellWritePermissionRequests,
	confirmSandboxPermission,
	findSessionGrant,
	getSandboxDenyRoots,
	getSandboxShellGrant,
	isDeniedSandboxPath,
	isPathInsideRoot,
	isSensitiveSandboxRequest,
	listSessionGrants,
	resolveSandboxPath,
	revokeAllSessionGrants,
	revokeSessionGrant,
	runWithSandboxShellGrant,
	type SandboxEcosystemPermissionRequest,
	type SandboxEcosystemPermissionResult,
	type SandboxPermissionCapability,
	type SandboxPermissionContext,
	type SandboxPermissionDecision,
	type SandboxPermissionPrompt,
	type SandboxPermissionRequest,
	type SandboxSessionGrantEntry,
	type SandboxShellGrant,
} from "../execution-mode/sandbox-permissions.js";
