import {
	BatchFlow,
	BatchTasks,
	ConceptMap,
	DataFlow,
	EvidenceGrid,
	Lifecycle,
	MediaFrame,
	Relationship,
	RelationshipChildren,
	RelationshipRoot,
} from "@/components/figures";
import {
	HomeActions,
	HomeEmphasis,
	HomeFlow,
	HomeFooter,
	HomeHero,
	HomeHeroCopy,
	HomeIndex,
	HomeIndexGroup,
	HomeIndexLink,
	HomeInlineLink,
	HomeLead,
	HomeMascot,
	HomeOutcomes,
	HomePrimary,
	HomeProduct,
	HomeProductBar,
	HomeProductCaption,
	HomeProductImage,
	HomeProof,
	HomeSecondary,
	HomeSection,
	HomeSectionHeading,
	HomeTitle,
} from "@/components/home";
import { DocsKicker } from "@/components/kicker";
import type { DocsLanguage } from "@/lib/i18n";
import {
	Beats,
	Checklist,
	Compare as ReadingCompare,
	CompareRow as ReadingCompareRow,
	Continue as ReadingContinue,
	ContinueLink,
	DocsCallout,
	DocsCard,
	DocsCards,
	Entries,
	Entry,
	Fork,
	ForkNo,
	ForkPane,
	ForkYes,
	Kit,
	KitItem,
	Panel,
	PanelGroup,
	PanelItem,
	Plate,
	Signal as ReadingSignal,
	Signals as ReadingSignals,
	Spread,
	Takeaways as ReadingTakeaways,
} from "@/components/reading";
import { Accordion, Accordions } from "fumadocs-ui/components/accordion";
import { File, Files, Folder } from "fumadocs-ui/components/files";
import { ImageZoom } from "fumadocs-ui/components/image-zoom";
import { Step, Steps } from "fumadocs-ui/components/steps";
import { Tab, Tabs } from "fumadocs-ui/components/tabs";
import { TypeTable } from "fumadocs-ui/components/type-table";
import defaultMdxComponents from "fumadocs-ui/mdx";
import type { MDXComponents } from "mdx/types";

export function getMDXComponents(language: DocsLanguage = "zh", components?: MDXComponents) {
	return {
		...defaultMdxComponents,
		Steps,
		Step,
		Tabs,
		Tab,
		Files,
		Folder,
		File,
		Accordions,
		Accordion,
		TypeTable,
		ImageZoom,
		Callout: DocsCallout,
		Card: DocsCard,
		Cards: DocsCards,
		DocsKicker,
		Takeaways: (props) => <ReadingTakeaways {...props} language={language} />,
		Kit,
		KitItem,
		Spread,
		Entries,
		Entry,
		Fork,
		ForkYes,
		ForkNo,
		ForkPane,
		Plate,
		Signals: (props) => <ReadingSignals {...props} language={language} />,
		Signal: (props) => <ReadingSignal {...props} language={language} />,
		Compare: (props) => <ReadingCompare {...props} language={language} />,
		CompareRow: (props) => <ReadingCompareRow {...props} language={language} />,
		Beats,
		Checklist,
		Panel,
		PanelGroup,
		PanelItem,
		Continue: (props) => <ReadingContinue {...props} language={language} />,
		ContinueLink,
		HomeHero,
		HomeHeroCopy,
		HomeTitle,
		HomeEmphasis,
		HomeLead,
		HomeActions,
		HomePrimary,
		HomeSecondary,
		HomeProof: (props) => <HomeProof {...props} language={language} />,
		HomeProduct,
		HomeProductBar,
		HomeProductImage,
		HomeProductCaption,
		HomeMascot,
		HomeSection,
		HomeSectionHeading,
		HomeFlow,
		HomeInlineLink,
		HomeIndex,
		HomeIndexGroup,
		HomeIndexLink,
		HomeOutcomes,
		HomeFooter,
		MediaFrame,
		ConceptMap,
		EvidenceGrid,
		Relationship,
		RelationshipRoot,
		RelationshipChildren,
		BatchFlow,
		BatchTasks,
		Lifecycle,
		DataFlow,
		...components,
	} satisfies MDXComponents;
}

export const useMDXComponents = (components?: MDXComponents) => getMDXComponents("zh", components);

declare global {
	type MDXProvidedComponents = ReturnType<typeof getMDXComponents>;
}
