/** @deprecated Internal consumers should import from `src/theme` instead. */
export {
	configureThemeRuntime,
	detectColorMode,
	detectTerminalBackground,
	getAvailableThemes,
	getAvailableThemesWithPaths,
	getLanguageFromPath,
	getResolvedThemeColors,
	getThemeByName,
	getThemeExportColors,
	highlightCode,
	initTheme,
	installBuiltinThemeDocuments,
	isLightTheme,
	loadThemeFromContent,
	onThemeChange,
	setRegisteredThemes,
	setTheme,
	setThemeInstance,
	stopThemeWatcher,
	Theme,
	type ThemeBg,
	type ThemeColor,
	type ThemeInfo,
	type ThemeRuntimeConfiguration,
	type ThemeWatchPort,
	theme,
} from "../../../theme/index.js";
