export const sanctumPageAssets = {
	achievementConnector: new URL("./assets/achievement-connector.webp", import.meta.url).href,
	achievementDisplayPanel: new URL("./assets/achievement-display-panel.webp", import.meta.url).href,
	achievementPanel: new URL("./assets/achievement-panel.webp", import.meta.url).href,
	backButton: new URL("./assets/back-button.webp", import.meta.url).href,
	bottomBar: {
		background: new URL("./assets/bottom-bar.webp", import.meta.url).href,
		book: new URL("./assets/bottom-bar-book.webp", import.meta.url).href,
		button: new URL("./assets/bottom-bar-button.webp", import.meta.url).href,
		compass: new URL("./assets/bottom-bar-compass.webp", import.meta.url).href,
		scroll: new URL("./assets/bottom-bar-scroll.webp", import.meta.url).href,
	},
	character: new URL("./assets/character.webp", import.meta.url).href,
	cultivationDigits: [
		new URL("./assets/cultivation-digit-0.webp", import.meta.url).href,
		new URL("./assets/cultivation-digit-1.webp", import.meta.url).href,
		new URL("./assets/cultivation-digit-2.webp", import.meta.url).href,
		new URL("./assets/cultivation-digit-3.webp", import.meta.url).href,
		new URL("./assets/cultivation-digit-4.webp", import.meta.url).href,
		new URL("./assets/cultivation-digit-5.webp", import.meta.url).href,
		new URL("./assets/cultivation-digit-6.webp", import.meta.url).href,
		new URL("./assets/cultivation-digit-7.webp", import.meta.url).href,
		new URL("./assets/cultivation-digit-8.webp", import.meta.url).href,
		new URL("./assets/cultivation-digit-9.webp", import.meta.url).href,
	],
	cultivationCompositionPanel: new URL("./assets/cultivation-composition-panel.webp", import.meta.url).href,
	cultivationPowerPanel: new URL("./assets/cultivation-power-panel.webp", import.meta.url).href,
	currentAchievementBackground: new URL("./assets/current-achievement-background.webp", import.meta.url).href,
	profilePanel: new URL("./assets/profile-panel.webp", import.meta.url).href,
	realmDetailActionButton: new URL("./assets/realm-detail-action-button.webp", import.meta.url).href,
	realmDetailPanel: new URL("./assets/realm-detail-panel.webp", import.meta.url).href,
	statusLabels: {
		completed: new URL("./assets/status-label-completed.webp", import.meta.url).href,
		current: new URL("./assets/status-label-current.webp", import.meta.url).href,
		locked: new URL("./assets/status-label-locked.webp", import.meta.url).href,
	},
	skills: [
		new URL("./assets/skill-01.webp", import.meta.url).href,
		new URL("./assets/skill-02.webp", import.meta.url).href,
		new URL("./assets/skill-03.webp", import.meta.url).href,
		new URL("./assets/skill-04.webp", import.meta.url).href,
	],
	achievements: {
		locked: [
			new URL("./assets/achievement-locked-01.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-02.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-03.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-04.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-05.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-06.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-07.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-08.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-09.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-10.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-11.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-12.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-13.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-14.webp", import.meta.url).href,
			new URL("./assets/achievement-locked-15.webp", import.meta.url).href,
		],
		unlocked: [
			new URL("./assets/achievement-unlocked-01.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-02.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-03.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-04.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-05.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-06.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-07.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-08.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-09.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-10.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-11.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-12.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-13.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-14.webp", import.meta.url).href,
			new URL("./assets/achievement-unlocked-15.webp", import.meta.url).href,
		],
	},
} as const;
