// Core session management

// Config paths
export { DEFAULT_SERVER_URL, getAgentDir, VERSION } from "./config.js";
// 工作模式（agent_mode 正交轴，见 ADR-0046）
export {
	type AgentMode,
	ALL_AGENT_MODES,
	DEFAULT_AGENT_MODE,
	isAgentMode,
	matchesAgentMode,
} from "./core/agent-mode.js";
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	type PromptResourceRef,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.js";
// Auth and model registry
export {
	type ApiKeyCredential,
	type AuthCredential,
	AuthStorage,
	type AuthStorageBackend,
	FileAuthStorageBackend,
	InMemoryAuthStorageBackend,
	type OAuthCredential,
} from "./core/auth-storage.js";
// Background bash tasks (run_in_background)
export {
	type BackgroundTaskEndedBy,
	type BackgroundTaskEvent,
	type BackgroundTaskListener,
	BackgroundTaskManager,
	type BackgroundTaskSnapshot,
	type BackgroundTaskStatus,
	buildTaskNotification,
} from "./core/background-tasks/index.js";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.js";
// Concurrency limiter (shared by OCR throttle, kb write mutex, KB processing session pool)
export { createLimiter, type Limiter } from "./core/concurrency-limit.js";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.js";
// Extension system
export type {
	AgentEndEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppAction,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	DirTreeToolCallEvent,
	EditToolCallEvent,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	FindToolResultEvent,
	GlobToolCallEvent,
	GlobToolResultEvent,
	GrepToolCallEvent,
	GrepToolResultEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MessageRenderer,
	MessageRenderOptions,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionForkEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionSwitchEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandLocation,
	SlashCommandSource,
	TerminalInputHandler,
	ToolCallEvent,
	ToolDefinition,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WriteToolCallEvent,
} from "./core/extensions/index.js";
export {
	createExtensionRuntime,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isDirTreeToolResult,
	isEditToolResult,
	isFindToolResult,
	isGlobToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
	wrapToolsWithExtensions,
	wrapToolWithExtensions,
} from "./core/extensions/index.js";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.js";
// Knowledge base core modules
export * as knowledge from "./core/knowledge/index.js";
export {
	convertToLlm,
	PROMPT_ATTACHMENT_CONTEXT_TYPE,
	PROMPT_ATTACHMENT_REFERENCE_TYPE,
	PROMPT_RESOURCE_REFERENCE_TYPE,
} from "./core/messages.js";
export { ModelRegistry } from "./core/model-registry.js";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.js";
export { DefaultPackageManager } from "./core/package-manager.js";
export { DEFAULT_PERSONA_ID, getPersonaPrompt, PERSONAS, type Persona } from "./core/personas.js";
export type { ResourceCollision, ResourceDiagnostic, ResourceLoader } from "./core/resource-loader.js";
export { DefaultResourceLoader } from "./core/resource-loader.js";
// SDK for programmatic usage
export {
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	// Factory
	createAgentSession,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createExtractTextFromImgTool,
	createExtractTextFromPdfTool,
	createFindTool,
	createGlobTool,
	createGrepTool,
	createHtmlToPdfTool,
	createLsTool,
	createProgressTool,
	createReadOnlyTools,
	createReadTool,
	createRenderPdfPageTool,
	createShellTool,
	createTreeTool,
	createWriteTool,
	type PromptTemplate,
	// Pre-built tools (use process.cwd())
	readOnlyTools,
} from "./core/sdk.js";
// 对话场景与工具 scope（隔离的唯一轴）
export {
	ALL_SCENARIOS,
	type CodingAgentTool,
	type ConversationScenario,
	DEFAULT_SCENARIO,
	type ToolCapability,
	type ToolCategory,
} from "./core/session/tool-scope.js";
export type { PromptAttachmentRef } from "./core/session/types.js";
export {
	type BranchSummaryEntry,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	loadEntriesFromFile,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.js";
export {
	type CompactionSettings,
	type ImageSettings,
	type PackageSource,
	type PersonalizationSettings,
	type RetrySettings,
	SettingsManager,
} from "./core/settings-manager.js";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.js";
// Subagents (extensible type registry; builtin explorer + workflow)
export {
	buildToolsForSubagentType,
	createDefaultSubagentSessionFactory,
	createDefaultSubagentTypeRegistry,
	createEmptySubagentTypeRegistry,
	createExplorerTypeDefinition,
	createSubagentControlTools,
	createWorkflowTypeDefinition,
	DISPATCH_WORKFLOWS_MAX_BATCH,
	EXPLORER_SYSTEM_PROMPT,
	isValidTaskName,
	SUBAGENT_CONTROL_TOOL_NAMES,
	SUBAGENT_TYPE_EXPLORER,
	SUBAGENT_TYPE_WORKFLOW,
	type SubagentChildHandle,
	SubagentCoordinator,
	type SubagentSessionFactory,
	type SubagentSnapshot,
	type SubagentStatus,
	type SubagentTodoProgress,
	type SubagentTypeDefinition,
	type SubagentTypeId,
	SubagentTypeRegistry,
	WORKFLOW_SYSTEM_PROMPT,
} from "./core/subagents/index.js";
export {
	createEditImageTool,
	createGenerateImageTool,
	type GenerateImageToolDetails,
	type ImageToolBackend,
	type ImageToolRef,
} from "./core/tools/generate-image/index.js";
// Tools
export {
	type AskUserQuestionAnswer,
	type AskUserQuestionCapability,
	type AskUserQuestionFn,
	type AskUserQuestionItem,
	type AskUserQuestionOption,
	type AskUserQuestionRequest,
	type AskUserQuestionResult,
	type AskUserQuestionToolDetails,
	type AskUserQuestionToolInput,
	type AskUserQuestionToolOptions,
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	bashTool,
	type CommandToolName,
	codingTools,
	createAskUserQuestionTool,
	createTaskOutputTool,
	createTaskStopTool,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type ExtractTextFromImgToolInput,
	type ExtractTextFromPdfToolInput,
	editTool,
	extractTextFromImgTool,
	extractTextFromPdfTool,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	findTool,
	formatSize,
	type GlobOperations,
	type GlobToolDetails,
	type GlobToolInput,
	type GlobToolOptions,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	getDefaultCodingToolNames,
	getDefaultCommandToolName,
	globTool,
	grepTool,
	type HtmlToPdfToolInput,
	htmlToPdfTool,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	lsTool,
	type ProgressToolDetails,
	type ProgressToolInput,
	progressTool,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	type RenderPdfPageToolInput,
	readTool,
	renderPdfPageTool,
	type ShellOperations,
	type ShellSpawnContext,
	type ShellSpawnHook,
	type ShellToolDetails,
	type ShellToolInput,
	type ShellToolOptions,
	shellTool,
	type TaskOutputToolDetails,
	type TaskOutputToolInput,
	type TaskOutputToolOptions,
	type TaskStopToolDetails,
	type TaskStopToolInput,
	type TaskStopToolOptions,
	type ToolsOptions,
	type TreeOperations,
	type TreeToolDetails,
	type TreeToolInput,
	type TreeToolOptions,
	type TruncationOptions,
	type TruncationResult,
	treeTool,
	truncateHead,
	truncateLine,
	truncateTail,
	type WriteOperations,
	type WriteToolInput,
	type WriteToolOptions,
	writeTool,
} from "./core/tools/index.js";
// Knowledge base tools
export {
	createKbFilterByTagsTool,
	type KbFilterByTagsDetails,
	type KbFilterByTagsInput,
	kbFilterByTagsTool,
} from "./core/tools/kb-filter-by-tags/index.js";
export {
	createKbListTagsTool,
	type KbListTagsDetails,
	type KbListTagsInput,
	kbListTagsTool,
} from "./core/tools/kb-list-tags/index.js";
export {
	createKbWritePageTool,
	type KbWritePageDetails,
	type KbWritePageInput,
	kbWritePageTool,
} from "./core/tools/kb-write-page/index.js";
// Main entry point
export { main } from "./main.js";
// Run modes for programmatic SDK usage
export {
	type PrintModeOptions,
	runPrintMode,
	runRpcMode,
} from "./modes/index.js";
// Theme utilities for custom tools and extensions (terminal rendering helpers removed with the TUI product)
export {
	getLanguageFromPath,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./modes/interactive/theme/theme.js";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.js";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.js";
// Shell utilities
export {
	decodeTextBuffer,
	getDefaultShellCommandPrefix,
	getShellConfig,
	isWindowsPowerShellShell,
	prependCommandPrefixes,
	WINDOWS_POWERSHELL_UTF8_COMMAND_PREFIX,
} from "./utils/shell.js";
