import { CAPABILITY_CONSTRAINT_KINDS, type CapabilityGrant, createCapabilityGrant } from "../../access.js";
import {
	DOMAIN_AGENT_SETTINGS_CAPABILITIES,
	DOMAIN_AI_CAPABILITIES,
	DOMAIN_BATCH_TASK_CAPABILITIES,
	DOMAIN_DOWNLOAD_CAPABILITIES,
	DOMAIN_GENERAL_SETTINGS_CAPABILITIES,
	DOMAIN_IM_CAPABILITIES,
	DOMAIN_KNOWLEDGE_CAPABILITIES,
	DOMAIN_MCP_CAPABILITIES,
	DOMAIN_MEDIA_CAPABILITIES,
	DOMAIN_MODEL_CAPABILITIES,
	DOMAIN_PROJECT_CAPABILITIES,
	DOMAIN_QUICK_PANEL_CAPABILITIES,
	DOMAIN_SCHEDULER_CAPABILITIES,
	DOMAIN_SESSION_CAPABILITIES,
	DOMAIN_SHORTCUT_CAPABILITIES,
	DOMAIN_SKILL_CAPABILITIES,
	DOMAIN_UPDATER_CAPABILITIES,
	DOMAIN_WEBHOOK_CAPABILITIES,
} from "../../domain.js";
import {
	FOUNDATION_ARTIFACT_CAPABILITIES,
	FOUNDATION_FILESYSTEM_CAPABILITIES,
	FOUNDATION_GATEWAY_CAPABILITIES,
	FOUNDATION_JOB_CAPABILITIES,
	FOUNDATION_NETWORK_CAPABILITIES,
	FOUNDATION_STORAGE_CAPABILITIES,
} from "../../foundation.js";
import { PLUGIN_CAPABILITY_PERMISSIONS } from "./types.js";

export function buildPluginCapabilityGrants(
	pluginId: string,
	permissions: ReadonlySet<string>,
	official: boolean,
): CapabilityGrant[] {
	const storageConstraints = [
		{
			kind: CAPABILITY_CONSTRAINT_KINDS.NAMESPACE,
			value: pluginId,
		},
	] as const;

	return [
		...(permissions.has(PLUGIN_CAPABILITY_PERMISSIONS.AI_MODELS_LIST)
			? [createCapabilityGrant(DOMAIN_AI_CAPABILITIES.LIST_MODELS)]
			: []),
		...(permissions.has(PLUGIN_CAPABILITY_PERMISSIONS.AI_COMPLETE)
			? [createCapabilityGrant(DOMAIN_AI_CAPABILITIES.COMPLETE)]
			: []),
		...(permissions.has(PLUGIN_CAPABILITY_PERMISSIONS.FILESYSTEM_READ)
			? [
					createCapabilityGrant(FOUNDATION_FILESYSTEM_CAPABILITIES.READ_DIRECTORY),
					createCapabilityGrant(FOUNDATION_FILESYSTEM_CAPABILITIES.READ_FILE),
					createCapabilityGrant(FOUNDATION_FILESYSTEM_CAPABILITIES.READ_BINARY_FILE),
					createCapabilityGrant(FOUNDATION_FILESYSTEM_CAPABILITIES.STAT),
					createCapabilityGrant(FOUNDATION_FILESYSTEM_CAPABILITIES.LIST_FILES_RECURSIVE),
				]
			: []),
		...(permissions.has(PLUGIN_CAPABILITY_PERMISSIONS.FILESYSTEM_WRITE)
			? [
					createCapabilityGrant(FOUNDATION_FILESYSTEM_CAPABILITIES.WRITE_FILE),
					createCapabilityGrant(FOUNDATION_FILESYSTEM_CAPABILITIES.RENAME),
					createCapabilityGrant(FOUNDATION_FILESYSTEM_CAPABILITIES.DELETE),
					createCapabilityGrant(FOUNDATION_FILESYSTEM_CAPABILITIES.MOVE),
					createCapabilityGrant(FOUNDATION_FILESYSTEM_CAPABILITIES.CREATE_DIRECTORY),
				]
			: []),
		...(permissions.has(PLUGIN_CAPABILITY_PERMISSIONS.NETWORK_FETCH)
			? [createCapabilityGrant(FOUNDATION_NETWORK_CAPABILITIES.REQUEST)]
			: []),
		...(permissions.has(PLUGIN_CAPABILITY_PERMISSIONS.STORAGE_READ)
			? [
					createCapabilityGrant(FOUNDATION_STORAGE_CAPABILITIES.READ_JSON, {
						constraints: storageConstraints,
					}),
					createCapabilityGrant(FOUNDATION_STORAGE_CAPABILITIES.LIST, {
						constraints: storageConstraints,
					}),
					createCapabilityGrant(FOUNDATION_STORAGE_CAPABILITIES.READ_FILE, {
						constraints: storageConstraints,
					}),
					createCapabilityGrant(FOUNDATION_STORAGE_CAPABILITIES.READ_BLOB, {
						constraints: storageConstraints,
					}),
					createCapabilityGrant(FOUNDATION_STORAGE_CAPABILITIES.GET_BLOB_REF, {
						constraints: storageConstraints,
					}),
				]
			: []),
		...(permissions.has(PLUGIN_CAPABILITY_PERMISSIONS.STORAGE_WRITE)
			? [
					createCapabilityGrant(FOUNDATION_STORAGE_CAPABILITIES.WRITE_JSON, {
						constraints: storageConstraints,
					}),
					createCapabilityGrant(FOUNDATION_STORAGE_CAPABILITIES.WRITE_FILE, {
						constraints: storageConstraints,
					}),
					createCapabilityGrant(FOUNDATION_STORAGE_CAPABILITIES.PUT_BLOB, {
						constraints: storageConstraints,
					}),
					createCapabilityGrant(FOUNDATION_STORAGE_CAPABILITIES.PUT_BLOB_FROM_FILE, {
						constraints: storageConstraints,
					}),
				]
			: []),
		...(permissions.has(PLUGIN_CAPABILITY_PERMISSIONS.MEDIA_GENERATE)
			? [
					createCapabilityGrant(DOMAIN_MEDIA_CAPABILITIES.LIST_PROVIDERS),
					createCapabilityGrant(DOMAIN_MEDIA_CAPABILITIES.SUBMIT),
					createCapabilityGrant(FOUNDATION_JOB_CAPABILITIES.GET),
					createCapabilityGrant(FOUNDATION_JOB_CAPABILITIES.CANCEL),
					createCapabilityGrant(FOUNDATION_ARTIFACT_CAPABILITIES.PERSIST),
					createCapabilityGrant(FOUNDATION_ARTIFACT_CAPABILITIES.RELEASE),
				]
			: []),
		...(official ? buildOfficialDomainGrants() : []),
	];
}

function buildOfficialDomainGrants(): CapabilityGrant[] {
	return [
		// 网关调用不挂可声明权限，只按来源收口给 official 插件（ADR-0056）
		createCapabilityGrant(FOUNDATION_GATEWAY_CAPABILITIES.REQUEST),
		createCapabilityGrant(DOMAIN_AGENT_SETTINGS_CAPABILITIES.GET_EXPERIMENTAL),
		createCapabilityGrant(DOMAIN_AGENT_SETTINGS_CAPABILITIES.SET_EXPERIMENTAL),
		createCapabilityGrant(DOMAIN_GENERAL_SETTINGS_CAPABILITIES.GET),
		createCapabilityGrant(DOMAIN_GENERAL_SETTINGS_CAPABILITIES.SET_NOTIFICATIONS),
		createCapabilityGrant(DOMAIN_GENERAL_SETTINGS_CAPABILITIES.SET_DEFAULT_EXECUTION_MODE),
		createCapabilityGrant(DOMAIN_GENERAL_SETTINGS_CAPABILITIES.SET_WORKSPACE),
		createCapabilityGrant(DOMAIN_IM_CAPABILITIES.GET_STATUS),
		createCapabilityGrant(DOMAIN_IM_CAPABILITIES.LIST_LOGS),
		createCapabilityGrant(DOMAIN_IM_CAPABILITIES.SET_ENABLED),
		createCapabilityGrant(DOMAIN_IM_CAPABILITIES.RESTART),
		createCapabilityGrant(DOMAIN_IM_CAPABILITIES.SET_AGENT_MODEL),
		createCapabilityGrant(DOMAIN_MODEL_CAPABILITIES.LIST),
		createCapabilityGrant(DOMAIN_MODEL_CAPABILITIES.GET_CONFIG),
		createCapabilityGrant(DOMAIN_MODEL_CAPABILITIES.GET_PROVIDER),
		createCapabilityGrant(DOMAIN_MODEL_CAPABILITIES.PROBE),
		createCapabilityGrant(DOMAIN_MODEL_CAPABILITIES.VALIDATE_KEY),
		createCapabilityGrant(DOMAIN_MODEL_CAPABILITIES.SET_DEFAULT),
		createCapabilityGrant(DOMAIN_MODEL_CAPABILITIES.UPSERT_PROVIDER),
		createCapabilityGrant(DOMAIN_MODEL_CAPABILITIES.REMOVE_PROVIDER),
		createCapabilityGrant(DOMAIN_MCP_CAPABILITIES.LIST_SERVERS),
		createCapabilityGrant(DOMAIN_MCP_CAPABILITIES.GET_SERVER),
		createCapabilityGrant(DOMAIN_MCP_CAPABILITIES.UPSERT_SERVER),
		createCapabilityGrant(DOMAIN_MCP_CAPABILITIES.SET_SERVER_ENABLED),
		createCapabilityGrant(DOMAIN_MCP_CAPABILITIES.REMOVE_SERVER),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.LIST_PROJECTS),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.GET_PROJECT),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.CREATE_PROJECT),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.UPDATE_PROJECT),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.DELETE_PROJECT),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.RUN_TASK),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.RETRY_TASK),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.STOP_TASK),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.DELETE_TASK),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.RESUME_TASK),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.RESUME_TASK_WITH_TEXT),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.DELETE_TASK_SESSION),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.DELETE_ALL_TASKS),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.START_PROJECT),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.STOP_PROJECT),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.RESET_PROJECT),
		createCapabilityGrant(DOMAIN_BATCH_TASK_CAPABILITIES.RESET_FAILED_TASKS),
		createCapabilityGrant(DOMAIN_DOWNLOAD_CAPABILITIES.LIST),
		createCapabilityGrant(DOMAIN_DOWNLOAD_CAPABILITIES.CANCEL),
		createCapabilityGrant(DOMAIN_UPDATER_CAPABILITIES.GET_STATE),
		createCapabilityGrant(DOMAIN_UPDATER_CAPABILITIES.GET_CURRENT_VERSION),
		createCapabilityGrant(DOMAIN_UPDATER_CAPABILITIES.CHECK),
		createCapabilityGrant(DOMAIN_UPDATER_CAPABILITIES.DOWNLOAD),
		createCapabilityGrant(DOMAIN_UPDATER_CAPABILITIES.INSTALL),
		createCapabilityGrant(DOMAIN_UPDATER_CAPABILITIES.DISMISS),
		createCapabilityGrant(DOMAIN_UPDATER_CAPABILITIES.CANCEL),
		createCapabilityGrant(DOMAIN_KNOWLEDGE_CAPABILITIES.LIST_BASES),
		createCapabilityGrant(DOMAIN_KNOWLEDGE_CAPABILITIES.LIST_FILE_STATUSES),
		createCapabilityGrant(DOMAIN_KNOWLEDGE_CAPABILITIES.GET_PROCESSING_STATUS),
		createCapabilityGrant(DOMAIN_KNOWLEDGE_CAPABILITIES.GET_PROCESSING_SETTINGS),
		createCapabilityGrant(DOMAIN_KNOWLEDGE_CAPABILITIES.CREATE_BASE),
		createCapabilityGrant(DOMAIN_KNOWLEDGE_CAPABILITIES.RENAME_BASE),
		createCapabilityGrant(DOMAIN_KNOWLEDGE_CAPABILITIES.DELETE_BASE),
		createCapabilityGrant(DOMAIN_KNOWLEDGE_CAPABILITIES.ADD_FILES),
		createCapabilityGrant(DOMAIN_KNOWLEDGE_CAPABILITIES.DELETE_ENTRY),
		createCapabilityGrant(DOMAIN_KNOWLEDGE_CAPABILITIES.SCAN_NOW),
		createCapabilityGrant(DOMAIN_KNOWLEDGE_CAPABILITIES.RETRY_FAILED),
		createCapabilityGrant(DOMAIN_KNOWLEDGE_CAPABILITIES.SET_PROCESSING_SETTINGS),
		createCapabilityGrant(DOMAIN_PROJECT_CAPABILITIES.LIST),
		createCapabilityGrant(DOMAIN_PROJECT_CAPABILITIES.CREATE),
		createCapabilityGrant(DOMAIN_PROJECT_CAPABILITIES.OPEN),
		createCapabilityGrant(DOMAIN_PROJECT_CAPABILITIES.RENAME),
		createCapabilityGrant(DOMAIN_PROJECT_CAPABILITIES.ARCHIVE),
		createCapabilityGrant(DOMAIN_PROJECT_CAPABILITIES.UNARCHIVE),
		createCapabilityGrant(DOMAIN_PROJECT_CAPABILITIES.REMOVE),
		createCapabilityGrant(DOMAIN_SESSION_CAPABILITIES.LIST),
		createCapabilityGrant(DOMAIN_SESSION_CAPABILITIES.LIST_RUNTIME_PROJECTS),
		createCapabilityGrant(DOMAIN_SKILL_CAPABILITIES.LIST),
		createCapabilityGrant(DOMAIN_SKILL_CAPABILITIES.LIST_INSTALLED),
		createCapabilityGrant(DOMAIN_SKILL_CAPABILITIES.SET_ENABLED),
		createCapabilityGrant(DOMAIN_SKILL_CAPABILITIES.UNINSTALL),
		createCapabilityGrant(DOMAIN_SHORTCUT_CAPABILITIES.GET_SETTINGS),
		createCapabilityGrant(DOMAIN_SHORTCUT_CAPABILITIES.SET_BINDING),
		createCapabilityGrant(DOMAIN_SHORTCUT_CAPABILITIES.RESET_BINDING),
		createCapabilityGrant(DOMAIN_SHORTCUT_CAPABILITIES.RESET_ALL_BINDINGS),
		createCapabilityGrant(DOMAIN_QUICK_PANEL_CAPABILITIES.SET_TRIGGER),
		createCapabilityGrant(DOMAIN_QUICK_PANEL_CAPABILITIES.SET_POST_SEND_BEHAVIOR),
		createCapabilityGrant(DOMAIN_SCHEDULER_CAPABILITIES.LIST_TASKS),
		createCapabilityGrant(DOMAIN_SCHEDULER_CAPABILITIES.GET_TASK),
		createCapabilityGrant(DOMAIN_SCHEDULER_CAPABILITIES.LIST_HISTORY),
		createCapabilityGrant(DOMAIN_SCHEDULER_CAPABILITIES.CREATE_TASK),
		createCapabilityGrant(DOMAIN_SCHEDULER_CAPABILITIES.UPDATE_TASK),
		createCapabilityGrant(DOMAIN_SCHEDULER_CAPABILITIES.DELETE_TASK),
		createCapabilityGrant(DOMAIN_SCHEDULER_CAPABILITIES.SET_ENABLED),
		createCapabilityGrant(DOMAIN_SCHEDULER_CAPABILITIES.RUN_TASK),
		createCapabilityGrant(DOMAIN_SCHEDULER_CAPABILITIES.ABORT_TASK),
		createCapabilityGrant(DOMAIN_WEBHOOK_CAPABILITIES.LIST_ENDPOINTS),
		createCapabilityGrant(DOMAIN_WEBHOOK_CAPABILITIES.LIST_PROVIDERS),
		createCapabilityGrant(DOMAIN_WEBHOOK_CAPABILITIES.CREATE_ENDPOINT),
		createCapabilityGrant(DOMAIN_WEBHOOK_CAPABILITIES.UPDATE_ENDPOINT),
		createCapabilityGrant(DOMAIN_WEBHOOK_CAPABILITIES.DELETE_ENDPOINT),
		createCapabilityGrant(DOMAIN_WEBHOOK_CAPABILITIES.SET_ENABLED),
		createCapabilityGrant(DOMAIN_WEBHOOK_CAPABILITIES.TEST_ENDPOINT),
		createCapabilityGrant(DOMAIN_WEBHOOK_CAPABILITIES.SEND_MESSAGE),
	];
}
