export const EDIT_TOOL_DESCRIPTION = [
	"Edit a file surgically. Two modes — anchor mode (preferred) and exact-text mode.",
	"",
	"ANCHOR MODE (preferred): pass `edits`, an array of { anchor, end_anchor?, new_text, insert_after? }.",
	"- Anchors are the `line:hash` prefixes in read/grep/edit output (e.g. `42:h7x2` from a read line `42:h7x2→const x = 1;`). Copy them VERBATIM — never fabricate, compute, or guess an anchor; only tool output is a valid source.",
	"- The anchor is the WHOLE `line:hash` prefix. The line number is part of the anchor, NOT display decoration — passing the hash alone (e.g. `h7x2`) is wrong.",
	"- One edit replaces the anchor line (or the inclusive range anchor..end_anchor) with new_text. `end_anchor` is INCLUDED: if its line contains a closing brace, bracket, or JSX tag that should remain, reproduce that closer in new_text. Empty new_text deletes the range. insert_after: true inserts new_text after the anchor line instead.",
	"- No need to reproduce the old text — the anchor is the identity. This avoids whitespace/punctuation mismatch failures entirely.",
	"- The batch is ATOMIC: if any anchor is stale (file changed there), ALL edits are rejected and the error returns fresh anchors around each failed target — retry the full batch with those, without re-reading the file.",
	"- Line numbers in anchors are hints: if content merely moved a few lines, the edit finds it again automatically.",
	"- After a successful edit, the result includes fresh anchors around each change — use them to continue editing without re-reading.",
	"",
	"EXACT-TEXT MODE (fallback): pass oldText/newText. oldText must match exactly (including whitespace) and be unique in the file. Use only when you have no anchors for the target region.",
	"",
	"When to use `edit` vs `write`:",
	"- Use `edit` for modifying specific parts of an existing file (preferred for most changes)",
	"- Use `write` ONLY for creating new files or complete rewrites where most content changes",
	"- NEVER use bash commands (sed, awk, perl -i) for file editing — always use this tool",
	"",
	"You MUST read a file before editing it. Anchor mode enforces this mechanically — anchors only come from tool output.",
].join("\n");
