import type { IpcRenderer } from "electron";
import type { DesktopApi } from "../api.js";
import { onIpcEvent, subscribeById } from "./helper.js";

const CHANNELS = {
	CREATE: "vetta:session:create",
	LIST_PROJECTS: "vetta:session:list-projects",
	LIST_SESSIONS: "vetta:session:list-sessions",
	SESSIONS_CHANGED: "vetta:session:sessions-changed",
	PROMPT: "vetta:session:prompt",
	CONTINUE: "vetta:session:continue",
	ABORT: "vetta:session:abort",
	QUEUE_STATE: "vetta:session:queue-state",
	QUEUE_REMOVE: "vetta:session:queue-remove",
	QUEUE_REORDER: "vetta:session:queue-reorder",
	QUEUE_SEND_NOW: "vetta:session:queue-send-now",
	QUEUE_RESUME: "vetta:session:queue-resume",
	QUEUE_CLEAR: "vetta:session:queue-clear",
	CLEAR_TODOS: "vetta:session:clear-todos",
	SUBSCRIBE: "vetta:session:subscribe",
	UNSUBSCRIBE: "vetta:session:unsubscribe",
	UPDATE_SETTINGS: "vetta:session:update-settings",
	SET_EXECUTION_MODE: "vetta:session:set-execution-mode",
	SET_GLOBAL_EXECUTION_MODE: "vetta:session:set-global-execution-mode",
	SET_GLOBAL_AGENT_MODE: "vetta:session:set-global-agent-mode",
	AGENT_MODE_CHANGED: "vetta:session:agent-mode-changed",
	GET_STATE: "vetta:session:get-state",
	GET_MESSAGES: "vetta:session:get-messages",
	GET_FULL_HISTORY: "vetta:session:get-full-history",
	NAVIGATE_FOR_EDIT: "vetta:session:navigate-for-edit",
	SWITCH_BRANCH: "vetta:session:switch-branch",
	DELETE_MESSAGE: "vetta:session:delete-message",
	REPLACE_LAST_USER_MESSAGE: "vetta:session:replace-last-user-message",
	FORK_SESSION: "vetta:session:fork-session",
	CONFIRM_REQUEST: "vetta:session:confirm-request",
	CONFIRM_RESPONSE: "vetta:session:confirm-response",
	QUESTION_REQUEST: "vetta:session:question-request",
	QUESTION_LIST_PENDING: "vetta:session:question-list-pending",
	QUESTION_RESOLVED: "vetta:session:question-resolved",
	QUESTION_RESPONSE: "vetta:session:question-response",
	SANDBOX_GRANT_REQUEST: "vetta:session:sandbox-grant-request",
	SANDBOX_GRANT_RESPONSE: "vetta:session:sandbox-grant-response",
	SANDBOX_GRANTS_LIST: "vetta:session:sandbox-grants-list",
	SANDBOX_GRANTS_REVOKE: "vetta:session:sandbox-grants-revoke",
	SANDBOX_GRANTS_REVOKE_ALL: "vetta:session:sandbox-grants-revoke-all",
	BACKGROUND_TASKS_CLEAR_FINISHED: "vetta:session:background-tasks-clear-finished",
	BACKGROUND_TASKS_KILL: "vetta:session:background-tasks-kill",
	SUBAGENT_INTERRUPT: "vetta:session:subagent-interrupt",
	SET_GLOBAL_THINKING: "vetta:session:set-global-thinking-level",
	GET_GLOBAL_THINKING: "vetta:session:get-global-thinking-level",
	GET_PERSONAS: "vetta:session:get-personas",
	GET_PERSONALIZATION: "vetta:session:get-personalization",
	SET_PERSONALIZATION: "vetta:session:set-personalization",
	DELETE: "vetta:session:delete",
	DELETE_ALL_FOR_CWD: "vetta:session:delete-all-for-cwd",
	RENAME: "vetta:session:rename",
	AUTO_TITLE: "vetta:session:auto-title",
	NEXT_PROMPT_SUGGESTIONS: "vetta:session:next-prompt-suggestions",
	DISPOSE: "vetta:session:dispose",
	EVENT: "vetta:session:event",
	LIST_RUNNING: "vetta:session:list-running",
	LIST_RUNNING_CWDS: "vetta:session:list-running-cwds",
	RUNNING_CHANGED: "vetta:session:running-changed",
	CLEAR_DEFAULT_CONVERSATION: "vetta:session:clear-default-conversation",
	CLEAR_DEFAULT_ARTIFACTS: "vetta:session:clear-default-artifacts",
	VIEWER_OPEN: "vetta:session:viewer-open",
	VIEWER_SUBSCRIBE: "vetta:session:viewer-subscribe",
	VIEWER_UNSUBSCRIBE: "vetta:session:viewer-unsubscribe",
	VIEWER_EVENT: "vetta:session:viewer-event",
} as const;

export function createSessionApi(ipc: IpcRenderer): Pick<DesktopApi, "session"> {
	return {
		session: {
			create: (config, kind) => ipc.invoke(CHANNELS.CREATE, config, kind),
			listProjects: () => ipc.invoke(CHANNELS.LIST_PROJECTS),
			listSessions: (cwd) => ipc.invoke(CHANNELS.LIST_SESSIONS, cwd),
			onSessionsChanged: (handler) => onIpcEvent(ipc, CHANNELS.SESSIONS_CHANGED, handler),
			prompt: (sessionId, request) => ipc.invoke(CHANNELS.PROMPT, sessionId, request),
			continue: (sessionId) => ipc.invoke(CHANNELS.CONTINUE, sessionId),
			abort: (sessionId) => ipc.invoke(CHANNELS.ABORT, sessionId),
			getQueueState: (sessionId) => ipc.invoke(CHANNELS.QUEUE_STATE, sessionId),
			removeQueuedMessage: (sessionId, itemId) => ipc.invoke(CHANNELS.QUEUE_REMOVE, sessionId, itemId),
			reorderQueuedMessages: (sessionId, itemIds) => ipc.invoke(CHANNELS.QUEUE_REORDER, sessionId, itemIds),
			sendQueuedMessageNow: (sessionId, itemId) => ipc.invoke(CHANNELS.QUEUE_SEND_NOW, sessionId, itemId),
			resumeQueue: (sessionId) => ipc.invoke(CHANNELS.QUEUE_RESUME, sessionId),
			clearQueue: (sessionId) => ipc.invoke(CHANNELS.QUEUE_CLEAR, sessionId),
			clearTodos: (sessionId) => ipc.invoke(CHANNELS.CLEAR_TODOS, sessionId),
			subscribe: (sessionId, handler) =>
				subscribeById(ipc, CHANNELS.SUBSCRIBE, CHANNELS.EVENT, CHANNELS.UNSUBSCRIBE, handler, [sessionId]),
			onConfirmationRequest: (handler) => onIpcEvent(ipc, CHANNELS.CONFIRM_REQUEST, handler),
			respondToConfirmation: (requestId, confirmed) => ipc.invoke(CHANNELS.CONFIRM_RESPONSE, requestId, confirmed),
			onQuestionRequest: (handler) => onIpcEvent(ipc, CHANNELS.QUESTION_REQUEST, handler),
			listPendingQuestions: () => ipc.invoke(CHANNELS.QUESTION_LIST_PENDING),
			onQuestionResolved: (handler) => onIpcEvent(ipc, CHANNELS.QUESTION_RESOLVED, handler),
			respondToQuestion: (requestId, result) => ipc.invoke(CHANNELS.QUESTION_RESPONSE, requestId, result),
			onSandboxGrantRequest: (handler) => onIpcEvent(ipc, CHANNELS.SANDBOX_GRANT_REQUEST, handler),
			respondToSandboxGrant: (requestId, decision) =>
				ipc.invoke(CHANNELS.SANDBOX_GRANT_RESPONSE, requestId, decision),
			listSandboxGrants: (sessionId) => ipc.invoke(CHANNELS.SANDBOX_GRANTS_LIST, sessionId),
			revokeSandboxGrant: (sessionId, grantId) => ipc.invoke(CHANNELS.SANDBOX_GRANTS_REVOKE, sessionId, grantId),
			revokeAllSandboxGrants: (sessionId) => ipc.invoke(CHANNELS.SANDBOX_GRANTS_REVOKE_ALL, sessionId),
			clearFinishedBackgroundTasks: (sessionId) => ipc.invoke(CHANNELS.BACKGROUND_TASKS_CLEAR_FINISHED, sessionId),
			killBackgroundTask: (sessionId, taskId) => ipc.invoke(CHANNELS.BACKGROUND_TASKS_KILL, sessionId, taskId),
			interruptSubagent: (sessionId, target) => ipc.invoke(CHANNELS.SUBAGENT_INTERRUPT, sessionId, target),
			getSessionPath: (sessionId) => ipc.invoke("vetta:session:get-session-path", sessionId),
			updateSettings: (sessionId, partialSettings) =>
				ipc.invoke(CHANNELS.UPDATE_SETTINGS, sessionId, partialSettings),
			setExecutionMode: (sessionId, mode) => ipc.invoke(CHANNELS.SET_EXECUTION_MODE, sessionId, mode),
			setGlobalExecutionMode: (mode) => ipc.invoke(CHANNELS.SET_GLOBAL_EXECUTION_MODE, mode),
			setGlobalAgentMode: (mode) => ipc.invoke(CHANNELS.SET_GLOBAL_AGENT_MODE, mode),
			onAgentModeChanged: (handler) => onIpcEvent(ipc, CHANNELS.AGENT_MODE_CHANGED, handler),
			setGlobalThinkingLevel: (level) => ipc.invoke(CHANNELS.SET_GLOBAL_THINKING, level),
			getGlobalThinkingLevel: () => ipc.invoke(CHANNELS.GET_GLOBAL_THINKING),
			getPersonas: () => ipc.invoke(CHANNELS.GET_PERSONAS),
			getPersonalization: () => ipc.invoke(CHANNELS.GET_PERSONALIZATION),
			setPersonalization: (input) => ipc.invoke(CHANNELS.SET_PERSONALIZATION, input),
			getState: (sessionId) => ipc.invoke(CHANNELS.GET_STATE, sessionId),
			getMessages: (sessionId) => ipc.invoke(CHANNELS.GET_MESSAGES, sessionId),
			getFullHistory: (sessionId) => ipc.invoke(CHANNELS.GET_FULL_HISTORY, sessionId),
			navigateForEdit: (sessionId, entryId) => ipc.invoke(CHANNELS.NAVIGATE_FOR_EDIT, sessionId, entryId),
			switchBranch: (sessionId, entryId) => ipc.invoke(CHANNELS.SWITCH_BRANCH, sessionId, entryId),
			deleteMessage: (sessionId, entryId) => ipc.invoke(CHANNELS.DELETE_MESSAGE, sessionId, entryId),
			replaceLastUserMessage: (sessionId, entryId) =>
				ipc.invoke(CHANNELS.REPLACE_LAST_USER_MESSAGE, sessionId, entryId),
			forkSession: (sessionId, entryId) => ipc.invoke(CHANNELS.FORK_SESSION, sessionId, entryId),
			delete: (sessionPath) => ipc.invoke(CHANNELS.DELETE, sessionPath),
			deleteAllForCwd: (cwd) => ipc.invoke(CHANNELS.DELETE_ALL_FOR_CWD, cwd),
			rename: (sessionPath, name) => ipc.invoke(CHANNELS.RENAME, sessionPath, name),
			autoTitle: (sessionId, userText, assistantText) =>
				ipc.invoke(CHANNELS.AUTO_TITLE, sessionId, userText, assistantText),
			nextPromptSuggestions: (sessionId, conversation) =>
				ipc.invoke(CHANNELS.NEXT_PROMPT_SUGGESTIONS, sessionId, conversation),
			dispose: (sessionId) => ipc.invoke(CHANNELS.DISPOSE, sessionId),
			listRunning: () => ipc.invoke(CHANNELS.LIST_RUNNING),
			listRunningCwds: () => ipc.invoke(CHANNELS.LIST_RUNNING_CWDS),
			onRunningChanged: (handler) => onIpcEvent(ipc, CHANNELS.RUNNING_CHANGED, handler),
			clearDefaultConversation: (scope) => ipc.invoke(CHANNELS.CLEAR_DEFAULT_CONVERSATION, scope),
			clearDefaultArtifacts: (scope) => ipc.invoke(CHANNELS.CLEAR_DEFAULT_ARTIFACTS, scope),
			openViewer: (path) => ipc.invoke(CHANNELS.VIEWER_OPEN, path),
			subscribeViewer: (path, handler) =>
				subscribeById(ipc, CHANNELS.VIEWER_SUBSCRIBE, CHANNELS.VIEWER_EVENT, CHANNELS.VIEWER_UNSUBSCRIBE, handler, [
					path,
				]),
		},
	};
}
