import type { IpcRenderer } from "electron";
import type { DesktopApi } from "../api.js";
import { onIpcEvent, subscribeById } from "./helper.js";

const CHANNELS = {
	CREATE: "vetta:session:create",
	LIST_PROJECTS: "vetta:session:list-projects",
	LIST_SESSIONS: "vetta:session:list-sessions",
	PROMPT: "vetta:session:prompt",
	CONTINUE: "vetta:session:continue",
	ABORT: "vetta:session:abort",
	CLEAR_TODOS: "vetta:session:clear-todos",
	SUBSCRIBE: "vetta:session:subscribe",
	UNSUBSCRIBE: "vetta:session:unsubscribe",
	UPDATE_SETTINGS: "vetta:session:update-settings",
	SET_EXECUTION_MODE: "vetta:session:set-execution-mode",
	SET_GLOBAL_EXECUTION_MODE: "vetta:session:set-global-execution-mode",
	GET_STATE: "vetta:session:get-state",
	GET_MESSAGES: "vetta:session:get-messages",
	GET_FULL_HISTORY: "vetta:session:get-full-history",
	CONFIRM_REQUEST: "vetta:session:confirm-request",
	CONFIRM_RESPONSE: "vetta:session:confirm-response",
	QUESTION_REQUEST: "vetta:session:question-request",
	QUESTION_RESPONSE: "vetta:session:question-response",
	QUESTION_SET_ENABLED: "vetta:session:question-set-enabled",
	SANDBOX_GRANT_REQUEST: "vetta:session:sandbox-grant-request",
	SANDBOX_GRANT_RESPONSE: "vetta:session:sandbox-grant-response",
	SANDBOX_GRANTS_LIST: "vetta:session:sandbox-grants-list",
	SANDBOX_GRANTS_REVOKE: "vetta:session:sandbox-grants-revoke",
	SANDBOX_GRANTS_REVOKE_ALL: "vetta:session:sandbox-grants-revoke-all",
	BACKGROUND_TASKS_CLEAR_FINISHED: "vetta:session:background-tasks-clear-finished",
	SET_GLOBAL_THINKING: "vetta:session:set-global-thinking-level",
	GET_GLOBAL_THINKING: "vetta:session:get-global-thinking-level",
	SET_MAX_RECENT_IMAGES: "vetta:session:set-max-recent-images",
	GET_MAX_RECENT_IMAGES: "vetta:session:get-max-recent-images",
	GET_PERSONAS: "vetta:session:get-personas",
	GET_PERSONALIZATION: "vetta:session:get-personalization",
	SET_PERSONALIZATION: "vetta:session:set-personalization",
	DELETE: "vetta:session:delete",
	RENAME: "vetta:session:rename",
	AUTO_TITLE: "vetta:session:auto-title",
	NEXT_PROMPT_SUGGESTIONS: "vetta:session:next-prompt-suggestions",
	DISPOSE: "vetta:session:dispose",
	EVENT: "vetta:session:event",
	LIST_RUNNING: "vetta:session:list-running",
	RUNNING_CHANGED: "vetta:session:running-changed",
	CLEAR_DEFAULT_CONVERSATION: "vetta:session:clear-default-conversation",
	CLEAR_DEFAULT_ARTIFACTS: "vetta:session:clear-default-artifacts",
	VIEWER_OPEN: "vetta:session:viewer-open",
	VIEWER_SUBSCRIBE: "vetta:session:viewer-subscribe",
	VIEWER_UNSUBSCRIBE: "vetta:session:viewer-unsubscribe",
	VIEWER_EVENT: "vetta:session:viewer-event",
} as const;

export function createSessionApi(ipc: IpcRenderer): Pick<DesktopApi, "session"> {
	return {
		session: {
			create: (config, kind) => ipc.invoke(CHANNELS.CREATE, config, kind),
			listProjects: () => ipc.invoke(CHANNELS.LIST_PROJECTS),
			listSessions: (cwd) => ipc.invoke(CHANNELS.LIST_SESSIONS, cwd),
			prompt: (sessionId, request) => ipc.invoke(CHANNELS.PROMPT, sessionId, request),
			continue: (sessionId) => ipc.invoke(CHANNELS.CONTINUE, sessionId),
			abort: (sessionId) => ipc.invoke(CHANNELS.ABORT, sessionId),
			clearTodos: (sessionId) => ipc.invoke(CHANNELS.CLEAR_TODOS, sessionId),
			subscribe: (sessionId, handler) =>
				subscribeById(ipc, CHANNELS.SUBSCRIBE, CHANNELS.EVENT, CHANNELS.UNSUBSCRIBE, handler, [sessionId]),
			onConfirmationRequest: (handler) => onIpcEvent(ipc, CHANNELS.CONFIRM_REQUEST, handler),
			respondToConfirmation: (requestId, confirmed) => ipc.invoke(CHANNELS.CONFIRM_RESPONSE, requestId, confirmed),
			onQuestionRequest: (handler) => onIpcEvent(ipc, CHANNELS.QUESTION_REQUEST, handler),
			respondToQuestion: (requestId, result) => ipc.invoke(CHANNELS.QUESTION_RESPONSE, requestId, result),
			setQuestionEnabled: (enabled) => ipc.invoke(CHANNELS.QUESTION_SET_ENABLED, enabled),
			onSandboxGrantRequest: (handler) => onIpcEvent(ipc, CHANNELS.SANDBOX_GRANT_REQUEST, handler),
			respondToSandboxGrant: (requestId, decision) =>
				ipc.invoke(CHANNELS.SANDBOX_GRANT_RESPONSE, requestId, decision),
			listSandboxGrants: (sessionId) => ipc.invoke(CHANNELS.SANDBOX_GRANTS_LIST, sessionId),
			revokeSandboxGrant: (sessionId, grantId) => ipc.invoke(CHANNELS.SANDBOX_GRANTS_REVOKE, sessionId, grantId),
			revokeAllSandboxGrants: (sessionId) => ipc.invoke(CHANNELS.SANDBOX_GRANTS_REVOKE_ALL, sessionId),
			clearFinishedBackgroundTasks: (sessionId) => ipc.invoke(CHANNELS.BACKGROUND_TASKS_CLEAR_FINISHED, sessionId),
			getSessionPath: (sessionId) => ipc.invoke("vetta:session:get-session-path", sessionId),
			updateSettings: (sessionId, partialSettings) =>
				ipc.invoke(CHANNELS.UPDATE_SETTINGS, sessionId, partialSettings),
			setExecutionMode: (sessionId, mode) => ipc.invoke(CHANNELS.SET_EXECUTION_MODE, sessionId, mode),
			setGlobalExecutionMode: (mode) => ipc.invoke(CHANNELS.SET_GLOBAL_EXECUTION_MODE, mode),
			setGlobalThinkingLevel: (level) => ipc.invoke(CHANNELS.SET_GLOBAL_THINKING, level),
			getGlobalThinkingLevel: () => ipc.invoke(CHANNELS.GET_GLOBAL_THINKING),
			setMaxRecentImages: (count) => ipc.invoke(CHANNELS.SET_MAX_RECENT_IMAGES, count),
			getMaxRecentImages: () => ipc.invoke(CHANNELS.GET_MAX_RECENT_IMAGES),
			getPersonas: () => ipc.invoke(CHANNELS.GET_PERSONAS),
			getPersonalization: () => ipc.invoke(CHANNELS.GET_PERSONALIZATION),
			setPersonalization: (input) => ipc.invoke(CHANNELS.SET_PERSONALIZATION, input),
			getState: (sessionId) => ipc.invoke(CHANNELS.GET_STATE, sessionId),
			getMessages: (sessionId) => ipc.invoke(CHANNELS.GET_MESSAGES, sessionId),
			getFullHistory: (sessionId) => ipc.invoke(CHANNELS.GET_FULL_HISTORY, sessionId),
			delete: (sessionPath) => ipc.invoke(CHANNELS.DELETE, sessionPath),
			rename: (sessionPath, name) => ipc.invoke(CHANNELS.RENAME, sessionPath, name),
			autoTitle: (sessionId, userText, assistantText) =>
				ipc.invoke(CHANNELS.AUTO_TITLE, sessionId, userText, assistantText),
			nextPromptSuggestions: (sessionId, conversation) =>
				ipc.invoke(CHANNELS.NEXT_PROMPT_SUGGESTIONS, sessionId, conversation),
			dispose: (sessionId) => ipc.invoke(CHANNELS.DISPOSE, sessionId),
			listRunning: () => ipc.invoke(CHANNELS.LIST_RUNNING),
			onRunningChanged: (handler) => onIpcEvent(ipc, CHANNELS.RUNNING_CHANGED, handler),
			clearDefaultConversation: (scope) => ipc.invoke(CHANNELS.CLEAR_DEFAULT_CONVERSATION, scope),
			clearDefaultArtifacts: (scope) => ipc.invoke(CHANNELS.CLEAR_DEFAULT_ARTIFACTS, scope),
			openViewer: (path) => ipc.invoke(CHANNELS.VIEWER_OPEN, path),
			subscribeViewer: (path, handler) =>
				subscribeById(ipc, CHANNELS.VIEWER_SUBSCRIBE, CHANNELS.VIEWER_EVENT, CHANNELS.VIEWER_UNSUBSCRIBE, handler, [
					path,
				]),
		},
	};
}
