/** @deprecated Protocol contracts now live in @vetta/runtime-mcp. */
export {
	type IMcpClient,
	isHttpServerConfig,
	isStdioServerConfig,
	type JsonRpcErrorResponse,
	type JsonRpcMessage,
	type JsonRpcNotification,
	type JsonRpcRequest,
	type JsonRpcResponse,
	type JsonRpcSuccessResponse,
	type McpCapabilities,
	type McpClientInfo,
	type McpConfig,
	type McpContent,
	type McpHttpServerConfig,
	type McpImageContent,
	type McpInitializeParams,
	type McpInitializeResult,
	type McpJsonObject,
	type McpManagerState,
	type McpPrompt,
	type McpPromptsListResult,
	type McpResource,
	type McpResourceContent,
	type McpResourceReadParams,
	type McpResourceReadResult,
	type McpResourcesListResult,
	type McpServerCommonConfig,
	type McpServerConfig,
	type McpServerInfo,
	type McpServerInstance,
	type McpServerStatus,
	type McpStdioServerConfig,
	type McpTextContent,
	type McpTool,
	type McpToolCallParams,
	type McpToolCallResult,
	type McpToolsListResult,
} from "@vetta/runtime-mcp";
