import type { AgentMessage, ToolPhase } from "@vetta/agent-core";
import type { ImageContent, Message, TextContent } from "@vetta/ai";
import { randomUUID } from "crypto";
import {
	appendFileSync,
	closeSync,
	existsSync,
	mkdirSync,
	openSync,
	readdirSync,
	readFileSync,
	readSync,
	statSync,
	writeFileSync,
} from "fs";
import { readdir, readFile, stat } from "fs/promises";
import { join, resolve } from "path";
import { getAgentDir as getDefaultAgentDir, getSessionsDir } from "../config.js";
import {
	type BashExecutionMessage,
	type CustomMessage,
	createBranchSummaryMessage,
	createCompactionSummaryMessage,
	createCustomMessage,
} from "./messages.js";
import { acquireSessionLock, type SessionLockHandle } from "./session-lock.js";

export { SessionLockError } from "./session-lock.js";

export const CURRENT_SESSION_VERSION = 3;

export interface SessionHeader {
	type: "session";
	version?: number; // v1 sessions don't have this
	id: string;
	timestamp: string;
	cwd: string;
	parentSession?: string;
	/**
	 * User-message entry id in the parent session that this session was forked from.
	 * Present on desktop exportFork / exportBranch when the host supplies it.
	 */
	parentEntryId?: string;
}

export interface NewSessionOptions {
	parentSession?: string;
}

export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
}

export interface SessionMessageEntry extends SessionEntryBase {
	type: "message";
	message: AgentMessage;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: "thinking_level_change";
	thinkingLevel: string;
}

export interface ModelChangeEntry extends SessionEntryBase {
	type: "model_change";
	provider: string;
	modelId: string;
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: "compaction";
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
	/** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
	fromHook?: boolean;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: "branch_summary";
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** True if generated by an extension, false if pi-generated */
	fromHook?: boolean;
}

/**
 * Custom entry for extensions to store extension-specific data in the session.
 * Use customType to identify your extension's entries.
 *
 * Purpose: Persist extension state across session reloads. On reload, extensions can
 * scan entries for their customType and reconstruct internal state.
 *
 * Does NOT participate in LLM context (ignored by buildSessionContext).
 * For injecting content into context, see CustomMessageEntry.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: "custom";
	customType: string;
	data?: T;
}

/** Label entry for user-defined bookmarks/markers on entries. */
export interface LabelEntry extends SessionEntryBase {
	type: "label";
	targetId: string;
	label: string | undefined;
}

/** Session metadata entry (e.g., user-defined display name). */
export interface SessionInfoEntry extends SessionEntryBase {
	type: "session_info";
	name?: string;
}

/**
 * Tool execution timing entry.
 *
 * Recorded once per tool call at tool_execution_end. Carries startedAt (absolute
 * ms), durationMs, and any phases the tool reported via ctx.phase(label).
 *
 * Deliberately a non-message SessionEntry: LLM providers only consume `message`
 * entries when building the API payload, so timing data never enters the prompt.
 * See docs/adr/0001-tool-timing-as-separate-session-entry.md.
 */
export interface ToolTimingEntry extends SessionEntryBase {
	type: "tool_timing";
	toolCallId: string;
	toolName: string;
	startedAt: number;
	durationMs: number;
	phases: ToolPhase[];
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Use customType to identify your extension's entries.
 *
 * Unlike CustomEntry, this DOES participate in LLM context.
 * The content is converted to a user message in buildSessionContext().
 * Use details for extension-specific metadata (not sent to LLM).
 *
 * display controls TUI rendering:
 * - false: hidden entirely
 * - true: rendered with distinct styling (different from user messages)
 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: "custom_message";
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
}

/** Session entry - has id/parentId for tree structure (returned by "read" methods in SessionManager) */
export type SessionEntry =
	| SessionMessageEntry
	| ThinkingLevelChangeEntry
	| ModelChangeEntry
	| CompactionEntry
	| BranchSummaryEntry
	| CustomEntry
	| CustomMessageEntry
	| LabelEntry
	| SessionInfoEntry
	| ToolTimingEntry;

/** Raw file entry (includes header) */
export type FileEntry = SessionHeader | SessionEntry;

/** Tree node for getTree() - defensive copy of session structure */
export interface SessionTreeNode {
	entry: SessionEntry;
	children: SessionTreeNode[];
	/** Resolved label for this entry, if any */
	label?: string;
}

export interface SessionContext {
	messages: AgentMessage[];
	thinkingLevel: string;
	model: { provider: string; modelId: string } | null;
}

export interface SessionInfo {
	path: string;
	id: string;
	/** Working directory where the session was started. Empty string for old sessions. */
	cwd: string;
	/** User-defined display name from session_info entries. */
	name?: string;
	/** Path to the parent session (if this session was forked). */
	parentSessionPath?: string;
	/** User entry id in the parent session this fork was created from. */
	parentEntryId?: string;
	created: Date;
	modified: Date;
	messageCount: number;
	firstMessage: string;
	allMessagesText: string;
	/** Trimmed preview (~120 chars) of the most recent user/assistant message text. */
	lastMessagePreview: string;
}

export type ReadonlySessionManager = Pick<
	SessionManager,
	| "getCwd"
	| "getSessionDir"
	| "getSessionId"
	| "getSessionFile"
	| "getLeafId"
	| "getLeafEntry"
	| "getEntry"
	| "getLabel"
	| "getBranch"
	| "getHeader"
	| "getEntries"
	| "getTree"
	| "getSessionName"
>;

/** Generate a unique short ID (8 hex chars, collision-checked) */
function generateId(byId: { has(id: string): boolean }): string {
	for (let i = 0; i < 100; i++) {
		const id = randomUUID().slice(0, 8);
		if (!byId.has(id)) return id;
	}
	// Fallback to full UUID if somehow we have collisions
	return randomUUID();
}

/** Migrate v1 → v2: add id/parentId tree structure. Mutates in place. */
function migrateV1ToV2(entries: FileEntry[]): void {
	const ids = new Set<string>();
	let prevId: string | null = null;

	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 2;
			continue;
		}

		entry.id = generateId(ids);
		entry.parentId = prevId;
		prevId = entry.id;

		// Convert firstKeptEntryIndex to firstKeptEntryId for compaction
		if (entry.type === "compaction") {
			const comp = entry as CompactionEntry & { firstKeptEntryIndex?: number };
			if (typeof comp.firstKeptEntryIndex === "number") {
				const targetEntry = entries[comp.firstKeptEntryIndex];
				if (targetEntry && targetEntry.type !== "session") {
					comp.firstKeptEntryId = targetEntry.id;
				}
				delete comp.firstKeptEntryIndex;
			}
		}
	}
}

/** Migrate v2 → v3: rename hookMessage role to custom. Mutates in place. */
function migrateV2ToV3(entries: FileEntry[]): void {
	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 3;
			continue;
		}

		// Update message entries with hookMessage role
		if (entry.type === "message") {
			const msgEntry = entry as SessionMessageEntry;
			if (msgEntry.message && (msgEntry.message as { role: string }).role === "hookMessage") {
				(msgEntry.message as { role: string }).role = "custom";
			}
		}
	}
}

/**
 * Run all necessary migrations to bring entries to current version.
 * Mutates entries in place. Returns true if any migration was applied.
 */
function migrateToCurrentVersion(entries: FileEntry[]): boolean {
	const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
	const version = header?.version ?? 1;

	if (version >= CURRENT_SESSION_VERSION) return false;

	if (version < 2) migrateV1ToV2(entries);
	if (version < 3) migrateV2ToV3(entries);

	return true;
}

/** Exported for testing */
export function migrateSessionEntries(entries: FileEntry[]): void {
	migrateToCurrentVersion(entries);
}

/** Exported for compaction.test.ts */
export function parseSessionEntries(content: string): FileEntry[] {
	const entries: FileEntry[] = [];
	const lines = content.trim().split("\n");

	for (const line of lines) {
		if (!line.trim()) continue;
		try {
			const entry = JSON.parse(line) as FileEntry;
			entries.push(entry);
		} catch {
			// Skip malformed lines
		}
	}

	return entries;
}

export function getLatestCompactionEntry(entries: SessionEntry[]): CompactionEntry | null {
	for (let i = entries.length - 1; i >= 0; i--) {
		if (entries[i].type === "compaction") {
			return entries[i] as CompactionEntry;
		}
	}
	return null;
}

/**
 * Build the session context from entries using tree traversal.
 * If leafId is provided, walks from that entry to root.
 * Handles compaction and branch summaries along the path.
 */
export function buildSessionContext(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionContext {
	// Build uuid index if not available
	if (!byId) {
		byId = new Map<string, SessionEntry>();
		for (const entry of entries) {
			byId.set(entry.id, entry);
		}
	}

	// Find leaf
	let leaf: SessionEntry | undefined;
	if (leafId === null) {
		// Explicitly null - return no messages (navigated to before first entry)
		return { messages: [], thinkingLevel: "off", model: null };
	}
	if (leafId) {
		leaf = byId.get(leafId);
	}
	if (!leaf) {
		// Fallback to last entry (when leafId is undefined)
		leaf = entries[entries.length - 1];
	}

	if (!leaf) {
		return { messages: [], thinkingLevel: "off", model: null };
	}

	// Walk from leaf to root, collecting path
	const path: SessionEntry[] = [];
	let current: SessionEntry | undefined = leaf;
	while (current) {
		path.unshift(current);
		current = current.parentId ? byId.get(current.parentId) : undefined;
	}

	// Extract settings and find compaction
	let thinkingLevel = "off";
	let model: { provider: string; modelId: string } | null = null;
	let compaction: CompactionEntry | null = null;

	for (const entry of path) {
		if (entry.type === "thinking_level_change") {
			thinkingLevel = entry.thinkingLevel;
		} else if (entry.type === "model_change") {
			model = { provider: entry.provider, modelId: entry.modelId };
		} else if (entry.type === "message" && entry.message.role === "assistant") {
			model = { provider: entry.message.provider, modelId: entry.message.model };
		} else if (entry.type === "compaction") {
			compaction = entry;
		}
	}

	// Build messages and collect corresponding entries
	// When there's a compaction, we need to:
	// 1. Emit summary first (entry = compaction)
	// 2. Emit kept messages (from firstKeptEntryId up to compaction)
	// 3. Emit messages after compaction
	const messages: AgentMessage[] = [];

	const appendMessage = (entry: SessionEntry) => {
		if (entry.type === "message") {
			messages.push(entry.message);
		} else if (entry.type === "custom_message") {
			messages.push(
				createCustomMessage(entry.customType, entry.content, entry.display, entry.details, entry.timestamp),
			);
		} else if (entry.type === "branch_summary" && entry.summary) {
			messages.push(createBranchSummaryMessage(entry.summary, entry.fromId, entry.timestamp));
		}
	};

	if (compaction) {
		// Emit summary first
		messages.push(createCompactionSummaryMessage(compaction.summary, compaction.tokensBefore, compaction.timestamp));

		// Find compaction index in path
		const compactionIdx = path.findIndex((e) => e.type === "compaction" && e.id === compaction.id);

		// Emit kept messages (before compaction, starting from firstKeptEntryId)
		let foundFirstKept = false;
		for (let i = 0; i < compactionIdx; i++) {
			const entry = path[i];
			if (entry.id === compaction.firstKeptEntryId) {
				foundFirstKept = true;
			}
			if (foundFirstKept) {
				appendMessage(entry);
			}
		}

		// Emit messages after compaction
		for (let i = compactionIdx + 1; i < path.length; i++) {
			const entry = path[i];
			appendMessage(entry);
		}
	} else {
		// No compaction - emit all messages, handle branch summaries and custom messages
		for (const entry of path) {
			appendMessage(entry);
		}
	}

	return { messages, thinkingLevel, model };
}

/**
 * Compute the default session directory for a cwd.
 * Encodes cwd into a safe directory name under ~/.pi/agent/sessions/.
 */
function getDefaultSessionDir(cwd: string): string {
	const safePath = `--${cwd.replace(/^[/\\]/, "").replace(/[/\\:]/g, "-")}--`;
	const sessionDir = join(getDefaultAgentDir(), "sessions", safePath);
	if (!existsSync(sessionDir)) {
		mkdirSync(sessionDir, { recursive: true });
	}
	return sessionDir;
}

/** Exported for testing */
export function loadEntriesFromFile(filePath: string): FileEntry[] {
	if (!existsSync(filePath)) return [];

	const content = readFileSync(filePath, "utf8");
	const entries: FileEntry[] = [];
	const lines = content.trim().split("\n");

	for (const line of lines) {
		if (!line.trim()) continue;
		try {
			const entry = JSON.parse(line) as FileEntry;
			entries.push(entry);
		} catch {
			// Skip malformed lines
		}
	}

	// Validate session header
	if (entries.length === 0) return entries;
	const header = entries[0];
	if (header.type !== "session" || typeof (header as any).id !== "string") {
		return [];
	}

	return entries;
}

function isValidSessionFile(filePath: string): boolean {
	try {
		const fd = openSync(filePath, "r");
		const buffer = Buffer.alloc(512);
		const bytesRead = readSync(fd, buffer, 0, 512, 0);
		closeSync(fd);
		const firstLine = buffer.toString("utf8", 0, bytesRead).split("\n")[0];
		if (!firstLine) return false;
		const header = JSON.parse(firstLine);
		return header.type === "session" && typeof header.id === "string";
	} catch {
		return false;
	}
}

/** Exported for testing */
export function findMostRecentSession(sessionDir: string): string | null {
	try {
		const files = readdirSync(sessionDir)
			.filter((f) => f.endsWith(".jsonl"))
			.map((f) => join(sessionDir, f))
			.filter(isValidSessionFile)
			.map((path) => ({ path, mtime: statSync(path).mtime }))
			.sort((a, b) => b.mtime.getTime() - a.mtime.getTime());

		return files[0]?.path || null;
	} catch {
		return null;
	}
}

function isMessageWithContent(message: AgentMessage): message is Message {
	return typeof (message as Message).role === "string" && "content" in message;
}

function extractTextContent(message: Message): string {
	const content = message.content;
	if (typeof content === "string") {
		return content;
	}
	return content
		.filter((block): block is TextContent => block.type === "text")
		.map((block) => block.text)
		.join(" ");
}

function getLastActivityTime(entries: FileEntry[]): number | undefined {
	let lastActivityTime: number | undefined;

	for (const entry of entries) {
		if (entry.type !== "message") continue;

		const message = (entry as SessionMessageEntry).message;
		if (!isMessageWithContent(message)) continue;
		if (message.role !== "user" && message.role !== "assistant") continue;

		const msgTimestamp = (message as { timestamp?: number }).timestamp;
		if (typeof msgTimestamp === "number") {
			lastActivityTime = Math.max(lastActivityTime ?? 0, msgTimestamp);
			continue;
		}

		const entryTimestamp = (entry as SessionEntryBase).timestamp;
		if (typeof entryTimestamp === "string") {
			const t = new Date(entryTimestamp).getTime();
			if (!Number.isNaN(t)) {
				lastActivityTime = Math.max(lastActivityTime ?? 0, t);
			}
		}
	}

	return lastActivityTime;
}

function getSessionModifiedDate(entries: FileEntry[], header: SessionHeader, statsMtime: Date): Date {
	const lastActivityTime = getLastActivityTime(entries);
	if (typeof lastActivityTime === "number" && lastActivityTime > 0) {
		return new Date(lastActivityTime);
	}

	const headerTime = typeof header.timestamp === "string" ? new Date(header.timestamp).getTime() : NaN;
	return !Number.isNaN(headerTime) ? new Date(headerTime) : statsMtime;
}

async function buildSessionInfo(filePath: string): Promise<SessionInfo | null> {
	try {
		const content = await readFile(filePath, "utf8");
		const entries: FileEntry[] = [];
		const lines = content.trim().split("\n");

		for (const line of lines) {
			if (!line.trim()) continue;
			try {
				entries.push(JSON.parse(line) as FileEntry);
			} catch {
				// Skip malformed lines
			}
		}

		if (entries.length === 0) return null;
		const header = entries[0];
		if (header.type !== "session") return null;

		const stats = await stat(filePath);
		let messageCount = 0;
		let firstMessage = "";
		const allMessages: string[] = [];
		let name: string | undefined;

		for (const entry of entries) {
			// Extract session name (use latest)
			if (entry.type === "session_info") {
				const infoEntry = entry as SessionInfoEntry;
				if (infoEntry.name) {
					name = infoEntry.name.trim();
				}
			}

			if (entry.type !== "message") continue;
			messageCount++;

			const message = (entry as SessionMessageEntry).message;
			if (!isMessageWithContent(message)) continue;
			if (message.role !== "user" && message.role !== "assistant") continue;

			const textContent = extractTextContent(message);
			if (!textContent) continue;

			allMessages.push(textContent);
			if (!firstMessage && message.role === "user") {
				firstMessage = textContent;
			}
		}

		const cwd = typeof (header as SessionHeader).cwd === "string" ? (header as SessionHeader).cwd : "";
		const parentSessionPath = (header as SessionHeader).parentSession;
		const parentEntryId =
			typeof (header as SessionHeader).parentEntryId === "string"
				? (header as SessionHeader).parentEntryId
				: undefined;

		const modified = getSessionModifiedDate(entries, header as SessionHeader, stats.mtime);

		// 复用已解析的消息数组，取最后一条用户/助手消息正文做预览（约 120 字符）。
		const lastMessage = allMessages.length > 0 ? allMessages[allMessages.length - 1] : "";
		const lastMessagePreview = lastMessage.trim().slice(0, 120);

		return {
			path: filePath,
			id: (header as SessionHeader).id,
			cwd,
			name,
			parentSessionPath,
			parentEntryId,
			created: new Date((header as SessionHeader).timestamp),
			modified,
			messageCount,
			firstMessage: firstMessage || "(no messages)",
			allMessagesText: allMessages.join(" "),
			lastMessagePreview,
		};
	} catch {
		return null;
	}
}

export type SessionListProgress = (loaded: number, total: number) => void;

async function listSessionsFromDir(
	dir: string,
	onProgress?: SessionListProgress,
	progressOffset = 0,
	progressTotal?: number,
): Promise<SessionInfo[]> {
	const sessions: SessionInfo[] = [];
	if (!existsSync(dir)) {
		return sessions;
	}

	try {
		const dirEntries = await readdir(dir);
		const files = dirEntries.filter((f) => f.endsWith(".jsonl")).map((f) => join(dir, f));
		const total = progressTotal ?? files.length;

		let loaded = 0;
		const results = await Promise.all(
			files.map(async (file) => {
				const info = await buildSessionInfo(file);
				loaded++;
				onProgress?.(progressOffset + loaded, total);
				return info;
			}),
		);
		for (const info of results) {
			if (info) {
				sessions.push(info);
			}
		}
	} catch {
		// Return empty list on error
	}

	return sessions;
}

/**
 * Manages conversation sessions as trees stored in JSONL files.
 *
 * Each session entry has an id and parentId forming a tree structure. The "leaf"
 * pointer tracks the current position. Appending creates a child of the current leaf.
 * Branching moves the leaf to an earlier entry, allowing new branches without
 * modifying history.
 *
 * Use buildSessionContext() to get the resolved message list for the LLM, which
 * handles compaction summaries and follows the path from root to current leaf.
 */
export class SessionManager {
	private sessionId: string = "";
	private sessionFile: string | undefined;
	private sessionDir: string;
	private cwd: string;
	private persist: boolean;
	private flushed: boolean = false;
	/**
	 * Tracks whether the session header has been written to disk independently
	 * of the deferred body flush. New sessions write the header eagerly so
	 * external listers / fs.watch consumers (notably desktop-app's sidebar
	 * via im-gateway's state_patch) can see the file before the first
	 * assistant response triggers the full flush. _persist skips the header
	 * during initial flush if this is true to avoid duplicating it.
	 */
	private headerOnDisk: boolean = false;
	private fileEntries: FileEntry[] = [];
	private byId: Map<string, SessionEntry> = new Map();
	private labelsById: Map<string, string> = new Map();
	private leafId: string | null = null;
	private lockHandle?: SessionLockHandle;

	private constructor(
		cwd: string,
		sessionDir: string,
		sessionFile: string | undefined,
		persist: boolean,
		options?: NewSessionOptions,
	) {
		this.cwd = cwd;
		this.sessionDir = sessionDir;
		this.persist = persist;
		if (persist && sessionDir && !existsSync(sessionDir)) {
			mkdirSync(sessionDir, { recursive: true });
		}

		// setSessionFile / newSession will acquire the lock at the end of their
		// flow if persist is true. Constructor failures (incl. SessionLockError)
		// propagate to the caller; the partially-built instance has no lock yet.
		if (sessionFile) {
			this.setSessionFile(sessionFile);
		} else {
			this.newSession(options);
		}
	}

	/** Switch to a different session file (used for resume and branching) */
	setSessionFile(sessionFile: string): void {
		this.sessionFile = resolve(sessionFile);
		if (existsSync(this.sessionFile)) {
			this.fileEntries = loadEntriesFromFile(this.sessionFile);

			// If file was empty or corrupted (no valid header), truncate and start fresh
			// to avoid appending messages without a session header (which breaks the session)
			if (this.fileEntries.length === 0) {
				const explicitPath = this.sessionFile;
				this._newSessionInternal();
				this.sessionFile = explicitPath;
				this._rewriteFile();
				this.flushed = true;
				this._acquireLockForCurrentFile();
				return;
			}

			const header = this.fileEntries.find((e) => e.type === "session") as SessionHeader | undefined;
			this.sessionId = header?.id ?? randomUUID();

			let needsRewrite = false;
			if (migrateToCurrentVersion(this.fileEntries)) {
				needsRewrite = true;
			}

			if (needsRewrite) {
				this._rewriteFile();
			}

			this._buildIndex();
			this.flushed = true;
			this.headerOnDisk = true;
			this._acquireLockForCurrentFile();
		} else {
			const explicitPath = this.sessionFile;
			this._newSessionInternal();
			this.sessionFile = explicitPath; // preserve explicit path from --session flag
			this._acquireLockForCurrentFile();
			this._writeHeaderEagerly();
		}
	}

	newSession(options?: NewSessionOptions): string | undefined {
		this._newSessionInternal(options);
		this._acquireLockForCurrentFile();
		this._writeHeaderEagerly();
		return this.sessionFile;
	}

	/**
	 * Append the in-memory header to disk immediately after a fresh session
	 * is set up. This makes the .jsonl visible to external readers (e.g.
	 * desktop-app's listSessions, called in response to im-gateway's
	 * state_patch event) without waiting for the first assistant reply to
	 * trigger the deferred body flush in _persist.
	 */
	private _writeHeaderEagerly(): void {
		if (!this.persist || !this.sessionFile) return;
		if (this.headerOnDisk) return;
		const header = this.fileEntries[0];
		if (!header) return;
		appendFileSync(this.sessionFile, `${JSON.stringify(header)}\n`);
		this.headerOnDisk = true;
	}

	/**
	 * Reset internal state for a new session WITHOUT touching the file lock.
	 *
	 * Used by setSessionFile's empty/corrupt/missing-file fallback paths, which
	 * temporarily rotate sessionFile to a fresh path then immediately reassign
	 * it back to the explicit path. The caller must lock the *final* sessionFile
	 * itself via _acquireLockForCurrentFile.
	 */
	private _newSessionInternal(options?: NewSessionOptions): void {
		this.sessionId = randomUUID();
		const timestamp = new Date().toISOString();
		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: this.sessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: options?.parentSession,
		};
		this.fileEntries = [header];
		this.byId.clear();
		this.labelsById.clear();
		this.leafId = null;
		this.flushed = false;
		this.headerOnDisk = false;

		if (this.persist) {
			const fileTimestamp = timestamp.replace(/[:.]/g, "-");
			this.sessionFile = join(this.getSessionDir(), `${fileTimestamp}_${this.sessionId}.jsonl`);
		}
	}

	/**
	 * Release the previously held lock (if any) and acquire a fresh one for the
	 * current sessionFile. No-op for in-memory sessions.
	 *
	 * Throws SessionLockError if another live process holds the file.
	 */
	private _acquireLockForCurrentFile(): void {
		if (this.lockHandle) {
			this.lockHandle.release();
			this.lockHandle = undefined;
		}
		if (this.persist && this.sessionFile) {
			this.lockHandle = acquireSessionLock(this.sessionFile);
		}
	}

	/**
	 * Release the session file lock. Call when this manager will no longer be
	 * used. Idempotent. After close(), the manager must not be reused.
	 */
	close(): void {
		if (this.lockHandle) {
			this.lockHandle.release();
			this.lockHandle = undefined;
		}
	}

	private _buildIndex(): void {
		this.byId.clear();
		this.labelsById.clear();
		this.leafId = null;
		for (const entry of this.fileEntries) {
			if (entry.type === "session") continue;
			this.byId.set(entry.id, entry);
			this.leafId = entry.id;
			if (entry.type === "label") {
				if (entry.label) {
					this.labelsById.set(entry.targetId, entry.label);
				} else {
					this.labelsById.delete(entry.targetId);
				}
			}
		}
	}

	private _rewriteFile(): void {
		if (!this.persist || !this.sessionFile) return;
		const content = `${this.fileEntries.map((e) => JSON.stringify(e)).join("\n")}\n`;
		writeFileSync(this.sessionFile, content);
		this.headerOnDisk = true;
	}

	isPersisted(): boolean {
		return this.persist;
	}

	getCwd(): string {
		return this.cwd;
	}

	getSessionDir(): string {
		return this.sessionDir;
	}

	getSessionId(): string {
		return this.sessionId;
	}

	getSessionFile(): string | undefined {
		return this.sessionFile;
	}

	_persist(entry: SessionEntry): void {
		if (!this.persist || !this.sessionFile) return;

		const hasAssistant = this.fileEntries.some((e) => e.type === "message" && e.message.role === "assistant");
		if (!hasAssistant) {
			// Mark as not flushed so when assistant arrives, all entries get written
			this.flushed = false;
			return;
		}

		if (!this.flushed) {
			// Skip the header if it was already eagerly written when the session
			// was created — otherwise we'd duplicate it on first flush.
			const startIdx = this.headerOnDisk && this.fileEntries[0]?.type === "session" ? 1 : 0;
			for (let i = startIdx; i < this.fileEntries.length; i++) {
				appendFileSync(this.sessionFile, `${JSON.stringify(this.fileEntries[i])}\n`);
			}
			this.flushed = true;
			this.headerOnDisk = true;
		} else {
			appendFileSync(this.sessionFile, `${JSON.stringify(entry)}\n`);
		}
	}

	private _appendEntry(entry: SessionEntry): void {
		this.fileEntries.push(entry);
		this.byId.set(entry.id, entry);
		this.leafId = entry.id;
		this._persist(entry);
	}

	/** Append a message as child of current leaf, then advance leaf. Returns entry id.
	 * Does not allow writing CompactionSummaryMessage and BranchSummaryMessage directly.
	 * Reason: we want these to be top-level entries in the session, not message session entries,
	 * so it is easier to find them.
	 * These need to be appended via appendCompaction() and appendBranchSummary() methods.
	 */
	appendMessage(message: Message | CustomMessage | BashExecutionMessage): string {
		const entry: SessionMessageEntry = {
			type: "message",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			message,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a thinking level change as child of current leaf, then advance leaf. Returns entry id. */
	appendThinkingLevelChange(thinkingLevel: string): string {
		const entry: ThinkingLevelChangeEntry = {
			type: "thinking_level_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			thinkingLevel,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/**
	 * Append a tool timing entry as child of current leaf, then advance leaf.
	 * Returns entry id. Out-of-band metadata — never read by buildSessionContext,
	 * so this never enters LLM payloads.
	 */
	appendToolTiming(
		toolCallId: string,
		toolName: string,
		startedAt: number,
		durationMs: number,
		phases: ToolPhase[],
	): string {
		const entry: ToolTimingEntry = {
			type: "tool_timing",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			toolCallId,
			toolName,
			startedAt,
			durationMs,
			phases,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a model change as child of current leaf, then advance leaf. Returns entry id. */
	appendModelChange(provider: string, modelId: string): string {
		const entry: ModelChangeEntry = {
			type: "model_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			provider,
			modelId,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a compaction summary as child of current leaf, then advance leaf. Returns entry id. */
	appendCompaction<T = unknown>(
		summary: string,
		firstKeptEntryId: string,
		tokensBefore: number,
		details?: T,
		fromHook?: boolean,
	): string {
		const entry: CompactionEntry<T> = {
			type: "compaction",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			summary,
			firstKeptEntryId,
			tokensBefore,
			details,
			fromHook,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/**
	 * memory-mode rollover (ADR-0009). Start a FRESH session file seeded with the
	 * post-compaction state (summary + kept tail) and point its `parentSession`
	 * back at the file being rolled away. The new file is small, so im-gateway's
	 * per-message cold-start parse cost stays bounded even after a long-running
	 * conversation — this is the im-gateway-specific reason rollover exists where
	 * Hermes (a long-lived process) just compacts in place.
	 *
	 * Must be called AFTER {@link appendCompaction} has applied a compaction to
	 * the current branch: it carries that compaction's summary + kept tail into
	 * the new file. The compaction is re-homed as the new root, so
	 * buildSessionContext on the new file yields `summary + kept tail` — exactly
	 * the in-memory state — while the old file is left intact as an archive.
	 *
	 * Returns the { from, to } absolute paths (equal when nothing rolled: an
	 * in-memory session, or no compaction in the current branch).
	 */
	rolloverToNewFile(): { from: string | undefined; to: string | undefined } {
		const from = this.sessionFile;
		if (!this.persist) return { from, to: from };

		const path = this.getBranch();
		let compactionIdx = -1;
		for (let i = path.length - 1; i >= 0; i--) {
			if (path[i].type === "compaction") {
				compactionIdx = i;
				break;
			}
		}
		if (compactionIdx === -1) return { from, to: from };

		const compaction = path[compactionIdx] as CompactionEntry;

		// Kept tail: entries from firstKeptEntryId (inclusive) up to the
		// compaction, plus anything appended after it (normally nothing right
		// after an auto-compaction, but stay general).
		const kept: SessionEntry[] = [];
		let foundFirstKept = false;
		for (let i = 0; i < compactionIdx; i++) {
			const e = path[i];
			if (e.id === compaction.firstKeptEntryId) foundFirstKept = true;
			if (foundFirstKept) kept.push(e);
		}
		for (let i = compactionIdx + 1; i < path.length; i++) kept.push(path[i]);

		// Build the new linear chain: compaction' (root) -> kept'... Entry ids are
		// unique within the old session and this is a brand-new byId map, so we
		// keep them and only rewrite parentId to form the chain. With the
		// compaction at the root, buildSessionContext emits summary + every later
		// entry, so firstKeptEntryId only needs to stay valid.
		const carried: SessionEntry[] = [compaction, ...kept];
		const newEntries: SessionEntry[] = [];
		let prevId: string | null = null;
		for (const e of carried) {
			newEntries.push({ ...e, parentId: prevId } as SessionEntry);
			prevId = e.id;
		}
		(newEntries[0] as CompactionEntry).firstKeptEntryId = kept.length > 0 ? kept[0].id : compaction.id;

		const newSessionId = randomUUID();
		const timestamp = new Date().toISOString();
		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: from,
		};

		if (this.lockHandle) {
			this.lockHandle.release();
			this.lockHandle = undefined;
		}
		this.sessionId = newSessionId;
		this.fileEntries = [header, ...newEntries];
		this.sessionFile = join(this.getSessionDir(), `${timestamp.replace(/[:.]/g, "-")}_${newSessionId}.jsonl`);
		this._buildIndex();
		this._rewriteFile();
		this.flushed = true;
		this.headerOnDisk = true;
		this._acquireLockForCurrentFile();

		return { from, to: this.sessionFile };
	}

	/** Append a custom entry (for extensions) as child of current leaf, then advance leaf. Returns entry id. */
	appendCustomEntry(customType: string, data?: unknown): string {
		const entry: CustomEntry = {
			type: "custom",
			customType,
			data,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a session info entry (e.g., display name). Returns entry id. */
	appendSessionInfo(name: string): string {
		const entry: SessionInfoEntry = {
			type: "session_info",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			name: name.trim(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Get the current session name from the latest session_info entry, if any. */
	getSessionName(): string | undefined {
		// Walk entries in reverse to find the latest session_info with a name
		const entries = this.getEntries();
		for (let i = entries.length - 1; i >= 0; i--) {
			const entry = entries[i];
			if (entry.type === "session_info" && entry.name) {
				return entry.name;
			}
		}
		return undefined;
	}

	/**
	 * Append a custom message entry (for extensions) that participates in LLM context.
	 * @param customType Extension identifier for filtering on reload
	 * @param content Message content (string or TextContent/ImageContent array)
	 * @param display Whether to show in TUI (true = styled display, false = hidden)
	 * @param details Optional extension-specific metadata (not sent to LLM)
	 * @returns Entry id
	 */
	appendCustomMessageEntry<T = unknown>(
		customType: string,
		content: string | (TextContent | ImageContent)[],
		display: boolean,
		details?: T,
	): string {
		const entry: CustomMessageEntry<T> = {
			type: "custom_message",
			customType,
			content,
			display,
			details,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	// =========================================================================
	// Tree Traversal
	// =========================================================================

	getLeafId(): string | null {
		return this.leafId;
	}

	getLeafEntry(): SessionEntry | undefined {
		return this.leafId ? this.byId.get(this.leafId) : undefined;
	}

	getEntry(id: string): SessionEntry | undefined {
		return this.byId.get(id);
	}

	/**
	 * Permanently delete one message while preserving its descendants.
	 * Children are reparented to the deleted message's parent, and label entries
	 * targeting the message are removed with the same reparenting rule.
	 */
	deleteMessage(entryId: string): { leafId: string | null } {
		const entry = this.byId.get(entryId);
		if (!entry || entry.type !== "message") {
			throw new Error(`Entry ${entryId} is not a message`);
		}

		const removedIds = new Set<string>([entryId]);
		for (const candidate of this.byId.values()) {
			if (candidate.type === "label" && candidate.targetId === entryId) {
				removedIds.add(candidate.id);
			}
		}

		const resolveSurvivingParent = (parentId: string | null): string | null => {
			let current = parentId;
			while (current && removedIds.has(current)) {
				current = this.byId.get(current)?.parentId ?? null;
			}
			return current;
		};

		const firstKeptReplacements = new Map<string, string>();
		for (const candidate of this.byId.values()) {
			if (candidate.type !== "compaction" || !removedIds.has(candidate.firstKeptEntryId)) continue;
			const path = this.getBranch(candidate.id);
			const removedIndex = path.findIndex((pathEntry) => removedIds.has(pathEntry.id));
			const replacement = path.slice(removedIndex + 1).find((pathEntry) => !removedIds.has(pathEntry.id));
			firstKeptReplacements.set(candidate.id, replacement?.id ?? candidate.id);
		}

		const previousLeafId = this.leafId;
		this.fileEntries = this.fileEntries
			.filter((candidate) => candidate.type === "session" || !removedIds.has(candidate.id))
			.map((candidate): FileEntry => {
				if (candidate.type === "session") return candidate;
				let next: SessionEntry = candidate;
				const parentId = resolveSurvivingParent(candidate.parentId);
				if (parentId !== candidate.parentId) {
					next = { ...next, parentId } as SessionEntry;
				}
				const firstKeptEntryId = firstKeptReplacements.get(candidate.id);
				if (next.type === "compaction" && firstKeptEntryId) {
					next = { ...next, firstKeptEntryId };
				}
				if (next.type === "branch_summary" && removedIds.has(next.fromId)) {
					next = { ...next, fromId: resolveSurvivingParent(next.fromId) ?? "root" };
				}
				return next;
			});

		this._buildIndex();
		if (previousLeafId && !removedIds.has(previousLeafId) && this.byId.has(previousLeafId)) {
			this.leafId = previousLeafId;
		} else {
			this.leafId = resolveSurvivingParent(previousLeafId);
		}
		this._rewriteFile();
		this.flushed = true;
		return { leafId: this.leafId };
	}

	/**
	 * Get all direct children of an entry.
	 * Pass `null` to list root entries (parentId === null).
	 */
	getChildren(parentId: string | null): SessionEntry[] {
		const children: SessionEntry[] = [];
		for (const entry of this.byId.values()) {
			if (entry.parentId === parentId) {
				children.push(entry);
			}
		}
		return children;
	}

	/**
	 * Walk from entryId following the newest child at each step until a leaf.
	 * Used when switching branches to show the tip of that subtree.
	 */
	resolveSubtreeTip(entryId: string): string {
		if (!this.byId.has(entryId)) {
			throw new Error(`Entry ${entryId} not found`);
		}
		let tipId = entryId;
		for (;;) {
			const children = this.getChildren(tipId).filter((e) => e.type !== "label");
			if (children.length === 0) break;
			children.sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());
			tipId = children[children.length - 1]!.id;
		}
		return tipId;
	}

	/**
	 * Tip of a single user turn: the user message plus its assistant/tool/custom
	 * descendants, but **not** the next user message (or anything under it).
	 *
	 * Used by desktop fork: forking a user bubble keeps that prompt and the AI
	 * reply for this turn, without later conversation turns.
	 */
	resolveUserTurnTip(userEntryId: string): string {
		const entry = this.byId.get(userEntryId);
		if (!entry || entry.type !== "message" || entry.message.role !== "user") {
			throw new Error(`Entry ${userEntryId} is not a user message`);
		}
		let tipId = userEntryId;
		for (;;) {
			const children = this.getChildren(tipId)
				.filter((e) => e.type !== "label")
				// Stop before the next user turn — do not walk into sibling/follow-up user messages.
				.filter((e) => !(e.type === "message" && e.message.role === "user"))
				.sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());
			if (children.length === 0) break;
			tipId = children[children.length - 1]!.id;
		}
		return tipId;
	}

	/**
	 * User-message siblings that share the same parent (for UI branch switchers).
	 * Sorted by timestamp ascending.
	 */
	getUserMessageSiblings(entryId: string): SessionEntry[] {
		const entry = this.byId.get(entryId);
		if (!entry || entry.type !== "message" || entry.message.role !== "user") {
			return [];
		}
		return this.getChildren(entry.parentId)
			.filter((e) => e.type === "message" && e.message.role === "user")
			.sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());
	}

	/**
	 * Get the label for an entry, if any.
	 */
	getLabel(id: string): string | undefined {
		return this.labelsById.get(id);
	}

	/**
	 * Set or clear a label on an entry.
	 * Labels are user-defined markers for bookmarking/navigation.
	 * Pass undefined or empty string to clear the label.
	 */
	appendLabelChange(targetId: string, label: string | undefined): string {
		if (!this.byId.has(targetId)) {
			throw new Error(`Entry ${targetId} not found`);
		}
		const entry: LabelEntry = {
			type: "label",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			targetId,
			label,
		};
		this._appendEntry(entry);
		if (label) {
			this.labelsById.set(targetId, label);
		} else {
			this.labelsById.delete(targetId);
		}
		return entry.id;
	}

	/**
	 * Walk from entry to root, returning all entries in path order.
	 * Includes all entry types (messages, compaction, model changes, etc.).
	 * Use buildSessionContext() to get the resolved messages for the LLM.
	 */
	getBranch(fromId?: string): SessionEntry[] {
		const path: SessionEntry[] = [];
		const startId = fromId ?? this.leafId;
		let current = startId ? this.byId.get(startId) : undefined;
		while (current) {
			path.unshift(current);
			current = current.parentId ? this.byId.get(current.parentId) : undefined;
		}
		return path;
	}

	/**
	 * Build the session context (what gets sent to the LLM).
	 * Uses tree traversal from current leaf.
	 */
	buildSessionContext(): SessionContext {
		return buildSessionContext(this.getEntries(), this.leafId, this.byId);
	}

	/**
	 * Get session header.
	 */
	getHeader(): SessionHeader | null {
		const h = this.fileEntries.find((e) => e.type === "session");
		return h ? (h as SessionHeader) : null;
	}

	/**
	 * Get all session entries (excludes header). Returns a shallow copy.
	 * Use appendXXX() to add entries and branch() to change the leaf pointer.
	 * Message deletion is an explicit destructive exception handled by deleteMessage().
	 */
	getEntries(): SessionEntry[] {
		return this.fileEntries.filter((e): e is SessionEntry => e.type !== "session");
	}

	/**
	 * Get the session as a tree structure. Returns a shallow defensive copy of all entries.
	 * A well-formed session has exactly one root (first entry with parentId === null).
	 * Orphaned entries (broken parent chain) are also returned as roots.
	 */
	getTree(): SessionTreeNode[] {
		const entries = this.getEntries();
		const nodeMap = new Map<string, SessionTreeNode>();
		const roots: SessionTreeNode[] = [];

		// Create nodes with resolved labels
		for (const entry of entries) {
			const label = this.labelsById.get(entry.id);
			nodeMap.set(entry.id, { entry, children: [], label });
		}

		// Build tree
		for (const entry of entries) {
			const node = nodeMap.get(entry.id)!;
			if (entry.parentId === null || entry.parentId === entry.id) {
				roots.push(node);
			} else {
				const parent = nodeMap.get(entry.parentId);
				if (parent) {
					parent.children.push(node);
				} else {
					// Orphan - treat as root
					roots.push(node);
				}
			}
		}

		// Sort children by timestamp (oldest first, newest at bottom)
		// Use iterative approach to avoid stack overflow on deep trees
		const stack: SessionTreeNode[] = [...roots];
		while (stack.length > 0) {
			const node = stack.pop()!;
			node.children.sort((a, b) => new Date(a.entry.timestamp).getTime() - new Date(b.entry.timestamp).getTime());
			stack.push(...node.children);
		}

		return roots;
	}

	// =========================================================================
	// Branching
	// =========================================================================

	/**
	 * Start a new branch from an earlier entry.
	 * Moves the leaf pointer to the specified entry. The next appendXXX() call
	 * will create a child of that entry, forming a new branch. Existing entries
	 * are not modified or deleted.
	 */
	branch(branchFromId: string): void {
		if (!this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		this.leafId = branchFromId;
	}

	/**
	 * Reset the leaf pointer to null (before any entries).
	 * The next appendXXX() call will create a new root entry (parentId = null).
	 * Use this when navigating to re-edit the first user message.
	 */
	resetLeaf(): void {
		this.leafId = null;
	}

	/**
	 * Start a new branch with a summary of the abandoned path.
	 * Same as branch(), but also appends a branch_summary entry that captures
	 * context from the abandoned conversation path.
	 */
	branchWithSummary(branchFromId: string | null, summary: string, details?: unknown, fromHook?: boolean): string {
		if (branchFromId !== null && !this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		this.leafId = branchFromId;
		const entry: BranchSummaryEntry = {
			type: "branch_summary",
			id: generateId(this.byId),
			parentId: branchFromId,
			timestamp: new Date().toISOString(),
			fromId: branchFromId ?? "root",
			summary,
			details,
			fromHook,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/**
	 * Build header + path entries for a branched session file without mutating this manager.
	 * `leafId === null` produces an empty conversation (header only).
	 */
	private _buildExportBranchContent(
		leafId: string | null,
		options?: { parentEntryId?: string },
	): {
		header: SessionHeader;
		pathWithoutLabels: SessionEntry[];
		labelEntries: LabelEntry[];
		newSessionFile: string;
	} {
		const previousSessionFile = this.sessionFile;
		const pathWithoutLabels = leafId === null ? [] : this.getBranch(leafId).filter((e) => e.type !== "label");
		if (leafId !== null && pathWithoutLabels.length === 0) {
			throw new Error(`Entry ${leafId} not found`);
		}

		const newSessionId = randomUUID();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(this.getSessionDir(), `${fileTimestamp}_${newSessionId}.jsonl`);

		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: this.persist ? previousSessionFile : undefined,
			parentEntryId: options?.parentEntryId,
		};

		const pathEntryIds = new Set(pathWithoutLabels.map((e) => e.id));
		const labelsToWrite: Array<{ targetId: string; label: string }> = [];
		for (const [targetId, label] of this.labelsById) {
			if (pathEntryIds.has(targetId)) {
				labelsToWrite.push({ targetId, label });
			}
		}

		const labelEntries: LabelEntry[] = [];
		let parentId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
		const usedIds = new Set(pathEntryIds);
		for (const { targetId, label } of labelsToWrite) {
			const labelEntry: LabelEntry = {
				type: "label",
				id: generateId(usedIds),
				parentId,
				timestamp: new Date().toISOString(),
				targetId,
				label,
			};
			usedIds.add(labelEntry.id);
			labelEntries.push(labelEntry);
			parentId = labelEntry.id;
		}

		return { header, pathWithoutLabels, labelEntries, newSessionFile };
	}

	/**
	 * Write a new session file containing only the path from root to leafId.
	 * Does NOT switch this manager away from the current session (safe for desktop hosts).
	 * `leafId === null` writes an empty session (header only).
	 * Returns the new file path, or undefined if not persisting.
	 */
	exportBranchToNewFile(leafId: string | null, options?: { parentEntryId?: string }): string | undefined {
		if (!this.persist) return undefined;
		if (!existsSync(this.getSessionDir())) {
			mkdirSync(this.getSessionDir(), { recursive: true });
		}
		const { header, pathWithoutLabels, labelEntries, newSessionFile } = this._buildExportBranchContent(
			leafId,
			options,
		);
		appendFileSync(newSessionFile, `${JSON.stringify(header)}\n`);
		for (const entry of pathWithoutLabels) {
			appendFileSync(newSessionFile, `${JSON.stringify(entry)}\n`);
		}
		for (const entry of labelEntries) {
			appendFileSync(newSessionFile, `${JSON.stringify(entry)}\n`);
		}
		return newSessionFile;
	}

	/**
	 * Create a new session file containing only the path from root to the specified leaf,
	 * and switch this manager to the new file (CLI /fork behavior).
	 * Returns the new session file path, or undefined if not persisting.
	 */
	createBranchedSession(leafId: string): string | undefined {
		const { header, pathWithoutLabels, labelEntries, newSessionFile } = this._buildExportBranchContent(leafId);

		if (this.persist) {
			if (!existsSync(this.getSessionDir())) {
				mkdirSync(this.getSessionDir(), { recursive: true });
			}
			// Release lock on old file before switching
			if (this.lockHandle) {
				this.lockHandle.release();
				this.lockHandle = undefined;
			}
			appendFileSync(newSessionFile, `${JSON.stringify(header)}\n`);
			for (const entry of pathWithoutLabels) {
				appendFileSync(newSessionFile, `${JSON.stringify(entry)}\n`);
			}
			for (const entry of labelEntries) {
				appendFileSync(newSessionFile, `${JSON.stringify(entry)}\n`);
			}
			this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
			this.sessionId = header.id;
			this.sessionFile = newSessionFile;
			this.flushed = true;
			this.headerOnDisk = true;
			this._buildIndex();
			this._acquireLockForCurrentFile();
			return newSessionFile;
		}

		this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
		this.sessionId = header.id;
		this._buildIndex();
		return undefined;
	}

	/**
	 * Create a new session.
	 * @param cwd Working directory (stored in session header)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 */
	static create(cwd: string, sessionDir?: string, options?: NewSessionOptions): SessionManager {
		const dir = sessionDir ?? getDefaultSessionDir(cwd);
		return new SessionManager(cwd, dir, undefined, true, options);
	}

	/**
	 * Open a specific session file.
	 * @param path Path to session file
	 * @param sessionDir Optional session directory for /new or /branch. If omitted, derives from file's parent.
	 * @param options Optional NewSessionOptions forwarded to the constructor for
	 *   any path that ends up creating a fresh session (empty/missing file).
	 */
	static open(path: string, sessionDir?: string, options?: NewSessionOptions): SessionManager {
		// Extract cwd from session header if possible, otherwise use process.cwd()
		const entries = loadEntriesFromFile(path);
		const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
		const cwd = header?.cwd ?? process.cwd();
		// If no sessionDir provided, derive from file's parent directory
		const dir = sessionDir ?? resolve(path, "..");
		return new SessionManager(cwd, dir, path, true, options);
	}

	/**
	 * Continue the most recent session, or create new if none.
	 * @param cwd Working directory
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 */
	static continueRecent(cwd: string, sessionDir?: string): SessionManager {
		const dir = sessionDir ?? getDefaultSessionDir(cwd);
		const mostRecent = findMostRecentSession(dir);
		if (mostRecent) {
			return new SessionManager(cwd, dir, mostRecent, true);
		}
		return new SessionManager(cwd, dir, undefined, true);
	}

	/** Create an in-memory session (no file persistence) */
	static inMemory(cwd: string = process.cwd()): SessionManager {
		return new SessionManager(cwd, "", undefined, false);
	}

	/**
	 * Fork a session from another project directory into the current project.
	 * Creates a new session in the target cwd with the full history from the source session.
	 * @param sourcePath Path to the source session file
	 * @param targetCwd Target working directory (where the new session will be stored)
	 * @param sessionDir Optional session directory. If omitted, uses default for targetCwd.
	 */
	static forkFrom(sourcePath: string, targetCwd: string, sessionDir?: string): SessionManager {
		const sourceEntries = loadEntriesFromFile(sourcePath);
		if (sourceEntries.length === 0) {
			throw new Error(`Cannot fork: source session file is empty or invalid: ${sourcePath}`);
		}

		const sourceHeader = sourceEntries.find((e) => e.type === "session") as SessionHeader | undefined;
		if (!sourceHeader) {
			throw new Error(`Cannot fork: source session has no header: ${sourcePath}`);
		}

		const dir = sessionDir ?? getDefaultSessionDir(targetCwd);
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		// Create new session file with new ID but forked content
		const newSessionId = randomUUID();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(dir, `${fileTimestamp}_${newSessionId}.jsonl`);

		// Write new header pointing to source as parent, with updated cwd
		const newHeader: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: targetCwd,
			parentSession: sourcePath,
		};
		appendFileSync(newSessionFile, `${JSON.stringify(newHeader)}\n`);

		// Copy all non-header entries from source
		for (const entry of sourceEntries) {
			if (entry.type !== "session") {
				appendFileSync(newSessionFile, `${JSON.stringify(entry)}\n`);
			}
		}

		return new SessionManager(targetCwd, dir, newSessionFile, true);
	}

	/**
	 * List all sessions for a directory.
	 * @param cwd Working directory (used to compute default session directory)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async list(cwd: string, sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]> {
		const dir = sessionDir ?? getDefaultSessionDir(cwd);
		const sessions = await listSessionsFromDir(dir, onProgress);
		sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
		return sessions;
	}

	/**
	 * List all sessions across all project directories.
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async listAll(onProgress?: SessionListProgress): Promise<SessionInfo[]> {
		const sessionsDir = getSessionsDir();

		try {
			if (!existsSync(sessionsDir)) {
				return [];
			}
			const entries = await readdir(sessionsDir, { withFileTypes: true });
			const dirs = entries.filter((e) => e.isDirectory()).map((e) => join(sessionsDir, e.name));

			// Count total files first for accurate progress
			let totalFiles = 0;
			const dirFiles: string[][] = [];
			for (const dir of dirs) {
				try {
					const files = (await readdir(dir)).filter((f) => f.endsWith(".jsonl"));
					dirFiles.push(files.map((f) => join(dir, f)));
					totalFiles += files.length;
				} catch {
					dirFiles.push([]);
				}
			}

			// Process all files with progress tracking
			let loaded = 0;
			const sessions: SessionInfo[] = [];
			const allFiles = dirFiles.flat();

			const results = await Promise.all(
				allFiles.map(async (file) => {
					const info = await buildSessionInfo(file);
					loaded++;
					onProgress?.(loaded, totalFiles);
					return info;
				}),
			);

			for (const info of results) {
				if (info) {
					sessions.push(info);
				}
			}

			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		} catch {
			return [];
		}
	}
}
