export const PLUGIN_CAPABILITY_CHANNELS = {
	OPEN_SESSION: "vetta:plugins:capabilities:open-session",
	CLOSE_SESSION: "vetta:plugins:capabilities:close-session",
	FS_READ_DIRECTORY: "vetta:plugins:capabilities:fs:read-directory",
	FS_READ_FILE: "vetta:plugins:capabilities:fs:read-file",
	FS_WRITE_FILE: "vetta:plugins:capabilities:fs:write-file",
	FS_STAT: "vetta:plugins:capabilities:fs:stat",
	FS_RENAME: "vetta:plugins:capabilities:fs:rename",
	FS_DELETE: "vetta:plugins:capabilities:fs:delete",
	FS_MOVE: "vetta:plugins:capabilities:fs:move",
	FS_CREATE_DIRECTORY: "vetta:plugins:capabilities:fs:create-directory",
	FS_LIST_FILES_RECURSIVE: "vetta:plugins:capabilities:fs:list-files-recursive",
	PROJECT_LIST: "vetta:plugins:capabilities:project:list",
	PROJECT_CREATE: "vetta:plugins:capabilities:project:create",
	PROJECT_OPEN: "vetta:plugins:capabilities:project:open",
	PROJECT_RENAME: "vetta:plugins:capabilities:project:rename",
	PROJECT_ARCHIVE: "vetta:plugins:capabilities:project:archive",
	PROJECT_UNARCHIVE: "vetta:plugins:capabilities:project:unarchive",
	PROJECT_REMOVE: "vetta:plugins:capabilities:project:remove",
	SESSION_LIST: "vetta:plugins:capabilities:session:list",
	SESSION_LIST_RUNTIME_PROJECTS: "vetta:plugins:capabilities:session:list-runtime-projects",
	DOWNLOAD_LIST: "vetta:plugins:capabilities:download:list",
	DOWNLOAD_CANCEL: "vetta:plugins:capabilities:download:cancel",
} as const;
