export const xianxiaAssets = {
	appBackground: new URL("./assets/app-background.webp", import.meta.url).href,
	buttonBackground: new URL("./assets/button-background.webp", import.meta.url).href,
	inputBarBackground: new URL("./assets/input-bar-background.webp", import.meta.url).href,
	newSessionSceneCompass: new URL("./assets/new-session-scene-compass.webp", import.meta.url).href,
	newSessionSceneCard: new URL("./assets/new-session-scene-card.webp", import.meta.url).href,
	newSessionSceneScroll: new URL("./assets/new-session-scene-scroll.webp", import.meta.url).href,
	newSessionSceneShield: new URL("./assets/new-session-scene-shield.webp", import.meta.url).href,
	newSessionSkillCard: new URL("./assets/new-session-skill-card.webp", import.meta.url).href,
	newSessionSkillMeditation: new URL("./assets/new-session-skill-meditation.webp", import.meta.url).href,
	newSessionSkillSword: new URL("./assets/new-session-skill-sword.webp", import.meta.url).href,
	newSessionSkillWheel: new URL("./assets/new-session-skill-wheel.webp", import.meta.url).href,
	whiteGlazeGourd: new URL("./assets/white-glaze-gourd.webp", import.meta.url).href,
	whiteGlazeImmortal: new URL("./assets/white-glaze-immortal.webp", import.meta.url).href,
} as const;
