// AUTO-GENERATED models.dev 目录快照。不要手改——跑 `bun run snapshot:models-dev` 重新生成。
// 网络不可达且无本地缓存时的兜底(见 ADR-0050);运行时拉到线上数据就覆盖它。
import type { ModelsDevCatalog } from "./models-dev.js";

export const MODELS_DEV_SNAPSHOT: ModelsDevCatalog = {
	version: 2,
	fetchedAt: "2026-08-03T02:19:15.424Z",
	providers: {
		claude: {
			"claude-sonnet-4-6": {
				model: {
					id: "claude-sonnet-4-6",
					name: "Claude Sonnet 4.6",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high", "max"],
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 128000,
					cost: {
						input: 3,
						output: 15,
						cacheRead: 0.3,
						cacheWrite: 3.75,
					},
				},
				family: "claude-sonnet",
				releaseDate: "2026-02-17",
			},
			"claude-haiku-4-5": {
				model: {
					id: "claude-haiku-4-5",
					name: "Claude Haiku 4.5 (latest)",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 200000,
					maxTokens: 64000,
					cost: {
						input: 1,
						output: 5,
						cacheRead: 0.1,
						cacheWrite: 1.25,
					},
				},
				family: "claude-haiku",
				releaseDate: "2025-10-15",
			},
			"claude-opus-4-6": {
				model: {
					id: "claude-opus-4-6",
					name: "Claude Opus 4.6",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high", "max"],
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 128000,
					cost: {
						input: 5,
						output: 25,
						cacheRead: 0.5,
						cacheWrite: 6.25,
					},
				},
				family: "claude-opus",
				releaseDate: "2026-02-04",
			},
			"claude-fable-5": {
				model: {
					id: "claude-fable-5",
					name: "Claude Fable 5",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high", "xhigh", "max"],
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 128000,
					cost: {
						input: 10,
						output: 50,
						cacheRead: 1,
						cacheWrite: 12.5,
					},
				},
				family: "claude-fable",
				releaseDate: "2026-06-07",
			},
			"claude-opus-4-8": {
				model: {
					id: "claude-opus-4-8",
					name: "Claude Opus 4.8",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high", "xhigh", "max"],
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 128000,
					cost: {
						input: 5,
						output: 25,
						cacheRead: 0.5,
						cacheWrite: 6.25,
					},
				},
				family: "claude-opus",
				releaseDate: "2026-05-28",
			},
			"claude-opus-4-1": {
				model: {
					id: "claude-opus-4-1",
					name: "Claude Opus 4.1 (latest)",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 200000,
					maxTokens: 32000,
					cost: {
						input: 15,
						output: 75,
						cacheRead: 1.5,
						cacheWrite: 18.75,
					},
				},
				family: "claude-opus",
				releaseDate: "2025-08-05",
			},
			"claude-sonnet-4-5": {
				model: {
					id: "claude-sonnet-4-5",
					name: "Claude Sonnet 4.5 (latest)",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 64000,
					cost: {
						input: 3,
						output: 15,
						cacheRead: 0.3,
						cacheWrite: 3.75,
					},
				},
				family: "claude-sonnet",
				releaseDate: "2025-09-29",
			},
			"claude-sonnet-4-5-20250929": {
				model: {
					id: "claude-sonnet-4-5-20250929",
					name: "Claude Sonnet 4.5",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 64000,
					cost: {
						input: 3,
						output: 15,
						cacheRead: 0.3,
						cacheWrite: 3.75,
					},
				},
				family: "claude-sonnet",
				releaseDate: "2025-09-29",
			},
			"claude-opus-4-5-20251101": {
				model: {
					id: "claude-opus-4-5-20251101",
					name: "Claude Opus 4.5",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 200000,
					maxTokens: 64000,
					cost: {
						input: 5,
						output: 25,
						cacheRead: 0.5,
						cacheWrite: 6.25,
					},
				},
				family: "claude-opus",
				releaseDate: "2025-11-24",
			},
			"claude-haiku-4-5-20251001": {
				model: {
					id: "claude-haiku-4-5-20251001",
					name: "Claude Haiku 4.5",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 200000,
					maxTokens: 64000,
					cost: {
						input: 1,
						output: 5,
						cacheRead: 0.1,
						cacheWrite: 1.25,
					},
				},
				family: "claude-haiku",
				releaseDate: "2025-10-15",
			},
			"claude-opus-4-7": {
				model: {
					id: "claude-opus-4-7",
					name: "Claude Opus 4.7",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high", "xhigh", "max"],
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 128000,
					cost: {
						input: 5,
						output: 25,
						cacheRead: 0.5,
						cacheWrite: 6.25,
					},
				},
				family: "claude-opus",
				releaseDate: "2026-04-14",
			},
			"claude-opus-4-5": {
				model: {
					id: "claude-opus-4-5",
					name: "Claude Opus 4.5 (latest)",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 200000,
					maxTokens: 64000,
					cost: {
						input: 5,
						output: 25,
						cacheRead: 0.5,
						cacheWrite: 6.25,
					},
				},
				family: "claude-opus",
				releaseDate: "2025-11-24",
			},
			"claude-sonnet-5": {
				model: {
					id: "claude-sonnet-5",
					name: "Claude Sonnet 5",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high", "xhigh", "max"],
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 128000,
					cost: {
						input: 2,
						output: 10,
						cacheRead: 0.2,
						cacheWrite: 2.5,
					},
				},
				family: "claude-sonnet",
				releaseDate: "2026-06-29",
			},
			"claude-opus-5": {
				model: {
					id: "claude-opus-5",
					name: "Claude Opus 5",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high", "xhigh", "max"],
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 128000,
					cost: {
						input: 5,
						output: 25,
						cacheRead: 0.5,
						cacheWrite: 6.25,
					},
				},
				family: "claude-opus",
				releaseDate: "2026-07-24",
			},
			"claude-opus-4-1-20250805": {
				model: {
					id: "claude-opus-4-1-20250805",
					name: "Claude Opus 4.1",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 200000,
					maxTokens: 32000,
					cost: {
						input: 15,
						output: 75,
						cacheRead: 1.5,
						cacheWrite: 18.75,
					},
				},
				family: "claude-opus",
				releaseDate: "2025-08-05",
			},
		},
		openai: {
			"gpt-5.2-pro": {
				model: {
					id: "gpt-5.2-pro",
					name: "GPT-5.2 Pro",
					reasoning: true,
					reasoningLevels: ["medium", "high", "xhigh"],
					input: ["text", "image"],
					contextWindow: 400000,
					maxTokens: 128000,
					cost: {
						input: 21,
						output: 168,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gpt-pro",
				releaseDate: "2025-12-11",
			},
			"gpt-5.5-pro": {
				model: {
					id: "gpt-5.5-pro",
					name: "GPT-5.5 Pro",
					reasoning: true,
					reasoningLevels: ["medium", "high", "xhigh"],
					input: ["text", "image"],
					contextWindow: 1050000,
					maxTokens: 128000,
					cost: {
						input: 30,
						output: 180,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gpt-pro",
				releaseDate: "2026-04-23",
			},
			"gpt-4.1-mini": {
				model: {
					id: "gpt-4.1-mini",
					name: "GPT-4.1 mini",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 1047576,
					maxTokens: 32768,
					cost: {
						input: 0.4,
						output: 1.6,
						cacheRead: 0.1,
						cacheWrite: 0,
					},
				},
				family: "gpt-mini",
				releaseDate: "2025-04-14",
			},
			"gpt-4o": {
				model: {
					id: "gpt-4o",
					name: "GPT-4o",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 128000,
					maxTokens: 16384,
					cost: {
						input: 2.5,
						output: 10,
						cacheRead: 1.25,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2024-05-13",
			},
			"gpt-5.3-codex-spark": {
				model: {
					id: "gpt-5.3-codex-spark",
					name: "GPT-5.3 Codex Spark",
					reasoning: true,
					reasoningLevels: ["none", "low", "medium", "high", "xhigh"],
					input: ["text", "image"],
					contextWindow: 128000,
					maxTokens: 32000,
					cost: {
						input: 1.75,
						output: 14,
						cacheRead: 0.175,
						cacheWrite: 0,
					},
				},
				family: "gpt-codex-spark",
				releaseDate: "2026-02-05",
			},
			"gpt-5.4-pro": {
				model: {
					id: "gpt-5.4-pro",
					name: "GPT-5.4 Pro",
					reasoning: true,
					reasoningLevels: ["medium", "high", "xhigh"],
					input: ["text", "image"],
					contextWindow: 1050000,
					maxTokens: 128000,
					cost: {
						input: 30,
						output: 180,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gpt-pro",
				releaseDate: "2026-03-05",
			},
			"gpt-5.6-sol": {
				model: {
					id: "gpt-5.6-sol",
					name: "GPT-5.6 Sol",
					reasoning: true,
					reasoningLevels: ["none", "low", "medium", "high", "xhigh", "max"],
					input: ["text", "image"],
					contextWindow: 1050000,
					maxTokens: 128000,
					cost: {
						input: 5,
						output: 30,
						cacheRead: 0.5,
						cacheWrite: 6.25,
					},
				},
				family: "gpt-sol",
				releaseDate: "2026-07-09",
			},
			"text-embedding-ada-002": {
				model: {
					id: "text-embedding-ada-002",
					name: "text-embedding-ada-002",
					reasoning: false,
					input: ["text"],
					contextWindow: 8192,
					maxTokens: 1536,
					cost: {
						input: 0.1,
						output: 0,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "text-embedding",
				releaseDate: "2022-12-15",
			},
			"gpt-4.1-nano": {
				model: {
					id: "gpt-4.1-nano",
					name: "GPT-4.1 nano",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 1047576,
					maxTokens: 32768,
					cost: {
						input: 0.1,
						output: 0.4,
						cacheRead: 0.025,
						cacheWrite: 0,
					},
				},
				family: "gpt-nano",
				releaseDate: "2025-04-14",
			},
			"gpt-5.2-chat-latest": {
				model: {
					id: "gpt-5.2-chat-latest",
					name: "GPT-5.2 Chat",
					reasoning: true,
					reasoningLevels: ["medium"],
					input: ["text", "image"],
					contextWindow: 128000,
					maxTokens: 16384,
					cost: {
						input: 1.75,
						output: 14,
						cacheRead: 0.175,
						cacheWrite: 0,
					},
				},
				family: "gpt-codex",
				releaseDate: "2025-12-11",
			},
			"o3-mini": {
				model: {
					id: "o3-mini",
					name: "o3-mini",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high"],
					input: ["text"],
					contextWindow: 200000,
					maxTokens: 100000,
					cost: {
						input: 1.1,
						output: 4.4,
						cacheRead: 0.55,
						cacheWrite: 0,
					},
				},
				family: "o-mini",
				releaseDate: "2024-12-20",
			},
			"gpt-image-1-mini": {
				model: {
					id: "gpt-image-1-mini",
					name: "gpt-image-1-mini",
					reasoning: false,
					input: ["text", "image"],
				},
				family: "gpt-image",
				releaseDate: "2025-09-26",
			},
			"gpt-5.5": {
				model: {
					id: "gpt-5.5",
					name: "GPT-5.5",
					reasoning: true,
					reasoningLevels: ["none", "low", "medium", "high", "xhigh"],
					input: ["text", "image"],
					contextWindow: 1050000,
					maxTokens: 128000,
					cost: {
						input: 5,
						output: 30,
						cacheRead: 0.5,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2026-04-23",
			},
			"o3-pro": {
				model: {
					id: "o3-pro",
					name: "o3-pro",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 200000,
					maxTokens: 100000,
					cost: {
						input: 20,
						output: 80,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "o-pro",
				releaseDate: "2025-06-10",
			},
			"gpt-4o-mini": {
				model: {
					id: "gpt-4o-mini",
					name: "GPT-4o mini",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 128000,
					maxTokens: 16384,
					cost: {
						input: 0.15,
						output: 0.6,
						cacheRead: 0.075,
						cacheWrite: 0,
					},
				},
				family: "gpt-mini",
				releaseDate: "2024-07-18",
			},
			"chatgpt-image-latest": {
				model: {
					id: "chatgpt-image-latest",
					name: "chatgpt-image-latest",
					reasoning: false,
					input: ["text", "image"],
				},
				family: "gpt-image",
				releaseDate: "2025-12-16",
			},
			"gpt-5": {
				model: {
					id: "gpt-5",
					name: "GPT-5",
					reasoning: true,
					reasoningLevels: ["minimal", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 400000,
					maxTokens: 128000,
					cost: {
						input: 1.25,
						output: 10,
						cacheRead: 0.125,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2025-08-07",
			},
			"gpt-realtime-2.1": {
				model: {
					id: "gpt-realtime-2.1",
					name: "GPT-Realtime-2.1",
					reasoning: true,
					reasoningLevels: ["minimal", "low", "medium", "high", "xhigh"],
					input: ["text", "image"],
					contextWindow: 128000,
					maxTokens: 32000,
					cost: {
						input: 4,
						output: 24,
						cacheRead: 0.4,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2026-07-06",
			},
			"gpt-3.5-turbo": {
				model: {
					id: "gpt-3.5-turbo",
					name: "GPT-3.5-turbo",
					reasoning: false,
					input: ["text"],
					contextWindow: 16385,
					maxTokens: 4096,
					cost: {
						input: 0.5,
						output: 1.5,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2023-03-01",
			},
			"gpt-4o-2024-05-13": {
				model: {
					id: "gpt-4o-2024-05-13",
					name: "GPT-4o (2024-05-13)",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 128000,
					maxTokens: 4096,
					cost: {
						input: 5,
						output: 15,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2024-05-13",
			},
			"gpt-4o-2024-11-20": {
				model: {
					id: "gpt-4o-2024-11-20",
					name: "GPT-4o (2024-11-20)",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 128000,
					maxTokens: 16384,
					cost: {
						input: 2.5,
						output: 10,
						cacheRead: 1.25,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2024-11-20",
			},
			"gpt-5.4": {
				model: {
					id: "gpt-5.4",
					name: "GPT-5.4",
					reasoning: true,
					reasoningLevels: ["none", "low", "medium", "high", "xhigh"],
					input: ["text", "image"],
					contextWindow: 1050000,
					maxTokens: 128000,
					cost: {
						input: 2.5,
						output: 15,
						cacheRead: 0.25,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2026-03-05",
			},
			"gpt-5.3-chat-latest": {
				model: {
					id: "gpt-5.3-chat-latest",
					name: "GPT-5.3 Chat (latest)",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 128000,
					maxTokens: 16384,
					cost: {
						input: 1.75,
						output: 14,
						cacheRead: 0.175,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2026-03-03",
			},
			"gpt-image-1.5": {
				model: {
					id: "gpt-image-1.5",
					name: "gpt-image-1.5",
					reasoning: false,
					input: ["text", "image"],
				},
				family: "gpt-image",
				releaseDate: "2025-11-25",
			},
			"gpt-5.4-nano": {
				model: {
					id: "gpt-5.4-nano",
					name: "GPT-5.4 nano",
					reasoning: true,
					reasoningLevels: ["none", "low", "medium", "high", "xhigh"],
					input: ["text", "image"],
					contextWindow: 400000,
					maxTokens: 128000,
					cost: {
						input: 0.2,
						output: 1.25,
						cacheRead: 0.02,
						cacheWrite: 0,
					},
				},
				family: "gpt-nano",
				releaseDate: "2026-03-17",
			},
			"gpt-5-pro": {
				model: {
					id: "gpt-5-pro",
					name: "GPT-5 Pro",
					reasoning: true,
					reasoningLevels: ["high"],
					input: ["text", "image"],
					contextWindow: 400000,
					maxTokens: 272000,
					cost: {
						input: 15,
						output: 120,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gpt-pro",
				releaseDate: "2025-10-06",
			},
			"gpt-5.4-mini": {
				model: {
					id: "gpt-5.4-mini",
					name: "GPT-5.4 mini",
					reasoning: true,
					reasoningLevels: ["none", "low", "medium", "high", "xhigh"],
					input: ["text", "image"],
					contextWindow: 400000,
					maxTokens: 128000,
					cost: {
						input: 0.75,
						output: 4.5,
						cacheRead: 0.075,
						cacheWrite: 0,
					},
				},
				family: "gpt-mini",
				releaseDate: "2026-03-17",
			},
			o1: {
				model: {
					id: "o1",
					name: "o1",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 200000,
					maxTokens: 100000,
					cost: {
						input: 15,
						output: 60,
						cacheRead: 7.5,
						cacheWrite: 0,
					},
				},
				family: "o",
				releaseDate: "2024-12-05",
			},
			"gpt-5.6-luna": {
				model: {
					id: "gpt-5.6-luna",
					name: "GPT-5.6 Luna",
					reasoning: true,
					reasoningLevels: ["none", "low", "medium", "high", "xhigh", "max"],
					input: ["text", "image"],
					contextWindow: 1050000,
					maxTokens: 128000,
					cost: {
						input: 0.2,
						output: 1.2,
						cacheRead: 0.02,
						cacheWrite: 0.25,
					},
				},
				family: "gpt-luna",
				releaseDate: "2026-07-09",
			},
			"gpt-5.2": {
				model: {
					id: "gpt-5.2",
					name: "GPT-5.2",
					reasoning: true,
					reasoningLevels: ["none", "low", "medium", "high", "xhigh"],
					input: ["text", "image"],
					contextWindow: 400000,
					maxTokens: 128000,
					cost: {
						input: 1.75,
						output: 14,
						cacheRead: 0.175,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2025-12-11",
			},
			"gpt-5.3-codex": {
				model: {
					id: "gpt-5.3-codex",
					name: "GPT-5.3 Codex",
					reasoning: true,
					reasoningLevels: ["none", "low", "medium", "high", "xhigh"],
					input: ["text", "image"],
					contextWindow: 400000,
					maxTokens: 128000,
					cost: {
						input: 1.75,
						output: 14,
						cacheRead: 0.175,
						cacheWrite: 0,
					},
				},
				family: "gpt-codex",
				releaseDate: "2026-02-05",
			},
			"gpt-5-mini": {
				model: {
					id: "gpt-5-mini",
					name: "GPT-5 Mini",
					reasoning: true,
					reasoningLevels: ["minimal", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 400000,
					maxTokens: 128000,
					cost: {
						input: 0.25,
						output: 2,
						cacheRead: 0.025,
						cacheWrite: 0,
					},
				},
				family: "gpt-mini",
				releaseDate: "2025-08-07",
			},
			"o1-pro": {
				model: {
					id: "o1-pro",
					name: "o1-pro",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 200000,
					maxTokens: 100000,
					cost: {
						input: 150,
						output: 600,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "o-pro",
				releaseDate: "2025-03-19",
			},
			"gpt-5.6": {
				model: {
					id: "gpt-5.6",
					name: "GPT-5.6",
					reasoning: true,
					reasoningLevels: ["none", "low", "medium", "high", "xhigh", "max"],
					input: ["text", "image"],
					contextWindow: 1050000,
					maxTokens: 128000,
					cost: {
						input: 5,
						output: 30,
						cacheRead: 0.5,
						cacheWrite: 6.25,
					},
				},
				family: "gpt-sol",
				releaseDate: "2026-07-09",
			},
			"gpt-5.1": {
				model: {
					id: "gpt-5.1",
					name: "GPT-5.1",
					reasoning: true,
					reasoningLevels: ["none", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 400000,
					maxTokens: 128000,
					cost: {
						input: 1.25,
						output: 10,
						cacheRead: 0.125,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2025-11-13",
			},
			"gpt-4-turbo": {
				model: {
					id: "gpt-4-turbo",
					name: "GPT-4 Turbo",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 128000,
					maxTokens: 4096,
					cost: {
						input: 10,
						output: 30,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2023-11-06",
			},
			"gpt-4o-2024-08-06": {
				model: {
					id: "gpt-4o-2024-08-06",
					name: "GPT-4o (2024-08-06)",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 128000,
					maxTokens: 16384,
					cost: {
						input: 2.5,
						output: 10,
						cacheRead: 1.25,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2024-08-06",
			},
			"gpt-5-nano": {
				model: {
					id: "gpt-5-nano",
					name: "GPT-5 Nano",
					reasoning: true,
					reasoningLevels: ["minimal", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 400000,
					maxTokens: 128000,
					cost: {
						input: 0.05,
						output: 0.4,
						cacheRead: 0.005,
						cacheWrite: 0,
					},
				},
				family: "gpt-nano",
				releaseDate: "2025-08-07",
			},
			o3: {
				model: {
					id: "o3",
					name: "o3",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 200000,
					maxTokens: 100000,
					cost: {
						input: 2,
						output: 8,
						cacheRead: 0.5,
						cacheWrite: 0,
					},
				},
				family: "o",
				releaseDate: "2025-04-16",
			},
			"gpt-5.6-terra": {
				model: {
					id: "gpt-5.6-terra",
					name: "GPT-5.6 Terra",
					reasoning: true,
					reasoningLevels: ["none", "low", "medium", "high", "xhigh", "max"],
					input: ["text", "image"],
					contextWindow: 1050000,
					maxTokens: 128000,
					cost: {
						input: 2,
						output: 12,
						cacheRead: 0.2,
						cacheWrite: 2.5,
					},
				},
				family: "gpt-terra",
				releaseDate: "2026-07-09",
			},
			"gpt-4.1": {
				model: {
					id: "gpt-4.1",
					name: "GPT-4.1",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 1047576,
					maxTokens: 32768,
					cost: {
						input: 2,
						output: 8,
						cacheRead: 0.5,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2025-04-14",
			},
			"o4-mini": {
				model: {
					id: "o4-mini",
					name: "o4-mini",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 200000,
					maxTokens: 100000,
					cost: {
						input: 1.1,
						output: 4.4,
						cacheRead: 0.275,
						cacheWrite: 0,
					},
				},
				family: "o-mini",
				releaseDate: "2025-04-16",
			},
			"gpt-4": {
				model: {
					id: "gpt-4",
					name: "GPT-4",
					reasoning: false,
					input: ["text"],
					contextWindow: 8192,
					maxTokens: 8192,
					cost: {
						input: 30,
						output: 60,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gpt",
				releaseDate: "2023-11-06",
			},
			"text-embedding-3-large": {
				model: {
					id: "text-embedding-3-large",
					name: "text-embedding-3-large",
					reasoning: false,
					input: ["text"],
					contextWindow: 8191,
					maxTokens: 3072,
					cost: {
						input: 0.13,
						output: 0,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "text-embedding",
				releaseDate: "2024-01-25",
			},
			"text-embedding-3-small": {
				model: {
					id: "text-embedding-3-small",
					name: "text-embedding-3-small",
					reasoning: false,
					input: ["text"],
					contextWindow: 8191,
					maxTokens: 1536,
					cost: {
						input: 0.02,
						output: 0,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "text-embedding",
				releaseDate: "2024-01-25",
			},
		},
		deepseek: {
			"deepseek-v4-flash": {
				model: {
					id: "deepseek-v4-flash",
					name: "DeepSeek V4 Flash",
					reasoning: true,
					reasoningLevels: ["high", "max"],
					input: ["text"],
					contextWindow: 1000000,
					maxTokens: 384000,
					cost: {
						input: 0.14,
						output: 0.28,
						cacheRead: 0.0028,
						cacheWrite: 0,
					},
				},
				family: "deepseek-flash",
				releaseDate: "2026-07-31",
			},
			"deepseek-v4-pro": {
				model: {
					id: "deepseek-v4-pro",
					name: "DeepSeek V4 Pro",
					reasoning: true,
					reasoningLevels: ["high", "max"],
					input: ["text"],
					contextWindow: 1000000,
					maxTokens: 384000,
					cost: {
						input: 0.435,
						output: 0.87,
						cacheRead: 0.003625,
						cacheWrite: 0,
					},
				},
				family: "deepseek-thinking",
				releaseDate: "2026-04-24",
			},
			"deepseek-chat": {
				model: {
					id: "deepseek-chat",
					name: "DeepSeek Chat",
					reasoning: false,
					input: ["text"],
					contextWindow: 1000000,
					maxTokens: 384000,
					cost: {
						input: 0.14,
						output: 0.28,
						cacheRead: 0.0028,
						cacheWrite: 0,
					},
				},
				family: "deepseek",
				releaseDate: "2025-12-01",
			},
			"deepseek-reasoner": {
				model: {
					id: "deepseek-reasoner",
					name: "DeepSeek Reasoner",
					reasoning: true,
					input: ["text"],
					contextWindow: 1000000,
					maxTokens: 384000,
					cost: {
						input: 0.14,
						output: 0.28,
						cacheRead: 0.0028,
						cacheWrite: 0,
					},
				},
				family: "deepseek-thinking",
				releaseDate: "2025-12-01",
			},
		},
		zai: {
			"glm-4.6v": {
				model: {
					id: "glm-4.6v",
					name: "GLM-4.6V",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 128000,
					maxTokens: 32768,
					cost: {
						input: 0.3,
						output: 0.9,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "glm",
				releaseDate: "2025-12-08",
			},
			"glm-5": {
				model: {
					id: "glm-5",
					name: "GLM-5",
					reasoning: true,
					input: ["text"],
					contextWindow: 204800,
					maxTokens: 131072,
					cost: {
						input: 1,
						output: 3.2,
						cacheRead: 0.2,
						cacheWrite: 0,
					},
				},
				family: "glm",
				releaseDate: "2026-02-12",
			},
			"glm-4.5-air": {
				model: {
					id: "glm-4.5-air",
					name: "GLM-4.5-Air",
					reasoning: true,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 98304,
					cost: {
						input: 0.2,
						output: 1.1,
						cacheRead: 0.03,
						cacheWrite: 0,
					},
				},
				family: "glm-air",
				releaseDate: "2025-07-28",
			},
			"glm-5.1": {
				model: {
					id: "glm-5.1",
					name: "GLM-5.1",
					reasoning: true,
					input: ["text"],
					contextWindow: 200000,
					maxTokens: 131072,
					cost: {
						input: 1.4,
						output: 4.4,
						cacheRead: 0.26,
						cacheWrite: 0,
					},
				},
				family: "glm",
				releaseDate: "2026-04-07",
			},
			"glm-4.7-flash": {
				model: {
					id: "glm-4.7-flash",
					name: "GLM-4.7-Flash",
					reasoning: true,
					input: ["text"],
					contextWindow: 200000,
					maxTokens: 131072,
					cost: {
						input: 0,
						output: 0,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "glm-flash",
				releaseDate: "2026-01-19",
			},
			"glm-5.2": {
				model: {
					id: "glm-5.2",
					name: "GLM-5.2",
					reasoning: true,
					reasoningLevels: ["high", "max"],
					input: ["text"],
					contextWindow: 1000000,
					maxTokens: 131072,
					cost: {
						input: 1.4,
						output: 4.4,
						cacheRead: 0.26,
						cacheWrite: 0,
					},
				},
				family: "glm",
				releaseDate: "2026-06-13",
			},
			"glm-4.7-flashx": {
				model: {
					id: "glm-4.7-flashx",
					name: "GLM-4.7-FlashX",
					reasoning: true,
					input: ["text"],
					contextWindow: 200000,
					maxTokens: 131072,
					cost: {
						input: 0.07,
						output: 0.4,
						cacheRead: 0.01,
						cacheWrite: 0,
					},
				},
				family: "glm-flash",
				releaseDate: "2026-01-19",
			},
			"glm-4.6": {
				model: {
					id: "glm-4.6",
					name: "GLM-4.6",
					reasoning: true,
					input: ["text"],
					contextWindow: 204800,
					maxTokens: 131072,
					cost: {
						input: 0.6,
						output: 2.2,
						cacheRead: 0.11,
						cacheWrite: 0,
					},
				},
				family: "glm",
				releaseDate: "2025-09-30",
			},
			"glm-4.5": {
				model: {
					id: "glm-4.5",
					name: "GLM-4.5",
					reasoning: true,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 98304,
					cost: {
						input: 0.6,
						output: 2.2,
						cacheRead: 0.11,
						cacheWrite: 0,
					},
				},
				family: "glm",
				releaseDate: "2025-07-28",
			},
			"glm-4.5v": {
				model: {
					id: "glm-4.5v",
					name: "GLM-4.5V",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 64000,
					maxTokens: 16384,
					cost: {
						input: 0.6,
						output: 1.8,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "glm",
				releaseDate: "2025-08-11",
			},
			"glm-4.7": {
				model: {
					id: "glm-4.7",
					name: "GLM-4.7",
					reasoning: true,
					input: ["text"],
					contextWindow: 204800,
					maxTokens: 131072,
					cost: {
						input: 0.6,
						output: 2.2,
						cacheRead: 0.11,
						cacheWrite: 0,
					},
				},
				family: "glm",
				releaseDate: "2025-12-22",
			},
			"glm-5-turbo": {
				model: {
					id: "glm-5-turbo",
					name: "GLM-5-Turbo",
					reasoning: true,
					input: ["text"],
					contextWindow: 200000,
					maxTokens: 131072,
					cost: {
						input: 1.2,
						output: 4,
						cacheRead: 0.24,
						cacheWrite: 0,
					},
				},
				family: "glm",
				releaseDate: "2026-03-16",
			},
			"glm-5v-turbo": {
				model: {
					id: "glm-5v-turbo",
					name: "GLM-5V-Turbo",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 200000,
					maxTokens: 131072,
					cost: {
						input: 1.2,
						output: 4,
						cacheRead: 0.24,
						cacheWrite: 0,
					},
				},
				family: "glm",
				releaseDate: "2026-04-01",
			},
			"glm-4.5-flash": {
				model: {
					id: "glm-4.5-flash",
					name: "GLM-4.5-Flash",
					reasoning: true,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 98304,
					cost: {
						input: 0,
						output: 0,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "glm-flash",
				releaseDate: "2025-07-28",
			},
		},
		kimi: {
			"kimi-k2.5": {
				model: {
					id: "kimi-k2.5",
					name: "Kimi K2.5",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 262144,
					maxTokens: 262144,
					cost: {
						input: 0.6,
						output: 3,
						cacheRead: 0.1,
						cacheWrite: 0,
					},
				},
				family: "kimi-k2",
				releaseDate: "2026-01-01",
			},
			"kimi-k2-thinking-turbo": {
				model: {
					id: "kimi-k2-thinking-turbo",
					name: "Kimi K2 Thinking Turbo",
					reasoning: true,
					input: ["text"],
					contextWindow: 262144,
					maxTokens: 262144,
					cost: {
						input: 1.15,
						output: 8,
						cacheRead: 0.15,
						cacheWrite: 0,
					},
				},
				family: "kimi-thinking",
				releaseDate: "2025-11-06",
			},
			"kimi-k2-0711-preview": {
				model: {
					id: "kimi-k2-0711-preview",
					name: "Kimi K2 0711",
					reasoning: false,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 16384,
					cost: {
						input: 0.6,
						output: 2.5,
						cacheRead: 0.15,
						cacheWrite: 0,
					},
				},
				family: "kimi-k2",
				releaseDate: "2025-07-14",
			},
			"kimi-k2.7-code-highspeed": {
				model: {
					id: "kimi-k2.7-code-highspeed",
					name: "Kimi K2.7 Code HighSpeed",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 262144,
					maxTokens: 262144,
					cost: {
						input: 1.9,
						output: 8,
						cacheRead: 0.38,
						cacheWrite: 0,
					},
				},
				family: "kimi-k2",
				releaseDate: "2026-06-12",
			},
			"kimi-k2.6": {
				model: {
					id: "kimi-k2.6",
					name: "Kimi K2.6",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 262144,
					maxTokens: 262144,
					cost: {
						input: 0.95,
						output: 4,
						cacheRead: 0.16,
						cacheWrite: 0,
					},
				},
				family: "kimi-k2",
				releaseDate: "2026-04-21",
			},
			"kimi-k2-turbo-preview": {
				model: {
					id: "kimi-k2-turbo-preview",
					name: "Kimi K2 Turbo",
					reasoning: false,
					input: ["text"],
					contextWindow: 262144,
					maxTokens: 262144,
					cost: {
						input: 2.4,
						output: 10,
						cacheRead: 0.6,
						cacheWrite: 0,
					},
				},
				family: "kimi-k2",
				releaseDate: "2025-09-05",
			},
			"kimi-k2-0905-preview": {
				model: {
					id: "kimi-k2-0905-preview",
					name: "Kimi K2 0905",
					reasoning: false,
					input: ["text"],
					contextWindow: 262144,
					maxTokens: 262144,
					cost: {
						input: 0.6,
						output: 2.5,
						cacheRead: 0.15,
						cacheWrite: 0,
					},
				},
				family: "kimi-k2",
				releaseDate: "2025-09-05",
			},
			"kimi-k2.7-code": {
				model: {
					id: "kimi-k2.7-code",
					name: "Kimi K2.7 Code",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 262144,
					maxTokens: 262144,
					cost: {
						input: 0.95,
						output: 4,
						cacheRead: 0.19,
						cacheWrite: 0,
					},
				},
				family: "kimi-k2",
				releaseDate: "2026-06-12",
			},
			"kimi-k2-thinking": {
				model: {
					id: "kimi-k2-thinking",
					name: "Kimi K2 Thinking",
					reasoning: true,
					input: ["text"],
					contextWindow: 262144,
					maxTokens: 262144,
					cost: {
						input: 0.6,
						output: 2.5,
						cacheRead: 0.15,
						cacheWrite: 0,
					},
				},
				family: "kimi-thinking",
				releaseDate: "2025-11-06",
			},
			"kimi-k3": {
				model: {
					id: "kimi-k3",
					name: "Kimi K3",
					reasoning: true,
					reasoningLevels: ["low", "high", "max"],
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 131072,
					cost: {
						input: 3,
						output: 15,
						cacheRead: 0.3,
						cacheWrite: 0,
					},
				},
				family: "kimi-k3",
				releaseDate: "2026-07-16",
			},
		},
		gemini: {
			"gemini-2.5-computer-use-preview-10-2025": {
				model: {
					id: "gemini-2.5-computer-use-preview-10-2025",
					name: "Gemini 2.5 Computer Use Preview 10-2025",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 65536,
					cost: {
						input: 1.25,
						output: 10,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gemini-pro",
				releaseDate: "2025-10-07",
			},
			"deep-research-preview-04-2026": {
				model: {
					id: "deep-research-preview-04-2026",
					name: "Deep Research Preview (Apr-21-2026)",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 65536,
					cost: {
						input: 2,
						output: 12,
						cacheRead: 0.2,
						cacheWrite: 0,
					},
				},
				family: "gemini-pro",
				releaseDate: "2026-04-21",
			},
			"gemini-flash-latest": {
				model: {
					id: "gemini-flash-latest",
					name: "Gemini Flash Latest",
					reasoning: true,
					reasoningLevels: ["minimal", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 1.5,
						output: 9,
						cacheRead: 0.15,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash",
				releaseDate: "2026-05-19",
			},
			"gemini-embedding-2": {
				model: {
					id: "gemini-embedding-2",
					name: "Gemini Embedding 2",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 8192,
					maxTokens: 1,
					cost: {
						input: 0.2,
						output: 0,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gemini",
				releaseDate: "2026-04-22",
			},
			"lyria-3-pro-preview": {
				model: {
					id: "lyria-3-pro-preview",
					name: "Lyria 3 Pro Preview",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 0,
						output: 0,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "lyria",
				releaseDate: "2026-03-25",
			},
			"gemini-3.5-flash": {
				model: {
					id: "gemini-3.5-flash",
					name: "Gemini 3.5 Flash",
					reasoning: true,
					reasoningLevels: ["minimal", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 1.5,
						output: 9,
						cacheRead: 0.15,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash",
				releaseDate: "2026-05-19",
			},
			"gemini-2.5-flash": {
				model: {
					id: "gemini-2.5-flash",
					name: "Gemini 2.5 Flash",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 0.3,
						output: 2.5,
						cacheRead: 0.03,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash",
				releaseDate: "2025-06-17",
			},
			"gemini-3.5-flash-lite": {
				model: {
					id: "gemini-3.5-flash-lite",
					name: "Gemini 3.5 Flash Lite",
					reasoning: true,
					reasoningLevels: ["minimal", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 0.3,
						output: 2.5,
						cacheRead: 0.03,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash-lite",
				releaseDate: "2026-07-21",
			},
			"lyria-3-clip-preview": {
				model: {
					id: "lyria-3-clip-preview",
					name: "Lyria 3 Clip Preview",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 0,
						output: 0,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "lyria",
				releaseDate: "2026-03-25",
			},
			"deep-research-max-preview-04-2026": {
				model: {
					id: "deep-research-max-preview-04-2026",
					name: "Deep Research Max Preview (Apr-21-2026)",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 65536,
					cost: {
						input: 2,
						output: 12,
						cacheRead: 0.2,
						cacheWrite: 0,
					},
				},
				family: "gemini-pro",
				releaseDate: "2026-04-21",
			},
			"gemini-3-pro-image-preview": {
				model: {
					id: "gemini-3-pro-image-preview",
					name: "Nano Banana Pro",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 32768,
					cost: {
						input: 2,
						output: 120,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gemini-pro",
				releaseDate: "2025-11-20",
			},
			"gemini-3.1-flash-lite-preview": {
				model: {
					id: "gemini-3.1-flash-lite-preview",
					name: "Gemini 3.1 Flash Lite Preview",
					reasoning: true,
					reasoningLevels: ["minimal", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 0.25,
						output: 1.5,
						cacheRead: 0.025,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash-lite",
				releaseDate: "2026-03-03",
			},
			"gemini-3.5-live-translate-preview": {
				model: {
					id: "gemini-3.5-live-translate-preview",
					name: "Gemini 3.5 Live Translate Preview",
					reasoning: false,
					contextWindow: 16384,
					maxTokens: 32768,
					cost: {
						input: 3.5,
						output: 21,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gemini-pro",
				releaseDate: "2026-06-09",
			},
			"gemini-3-flash-preview": {
				model: {
					id: "gemini-3-flash-preview",
					name: "Gemini 3 Flash Preview",
					reasoning: true,
					reasoningLevels: ["minimal", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 0.5,
						output: 3,
						cacheRead: 0.05,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash",
				releaseDate: "2025-12-17",
			},
			"gemini-3.1-pro-preview-customtools": {
				model: {
					id: "gemini-3.1-pro-preview-customtools",
					name: "Gemini 3.1 Pro Preview Custom Tools",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 2,
						output: 12,
						cacheRead: 0.2,
						cacheWrite: 0,
					},
				},
				family: "gemini-pro",
				releaseDate: "2026-02-19",
			},
			"gemini-3.1-flash-lite-image": {
				model: {
					id: "gemini-3.1-flash-lite-image",
					name: "Nano Banana 2 Lite",
					reasoning: true,
					reasoningLevels: ["minimal", "high"],
					input: ["text", "image"],
					contextWindow: 65536,
					maxTokens: 65536,
					cost: {
						input: 0.25,
						output: 30,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash-lite",
				releaseDate: "2026-06-30",
			},
			"gemini-3.1-flash-image-preview": {
				model: {
					id: "gemini-3.1-flash-image-preview",
					name: "Nano Banana 2",
					reasoning: true,
					reasoningLevels: ["minimal", "high"],
					input: ["text", "image"],
					contextWindow: 65536,
					maxTokens: 65536,
					cost: {
						input: 0.5,
						output: 60,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash",
				releaseDate: "2026-02-26",
			},
			"gemini-robotics-er-1.6-preview": {
				model: {
					id: "gemini-robotics-er-1.6-preview",
					name: "Gemini Robotics-ER 1.6 Preview",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 65536,
					cost: {
						input: 1,
						output: 5,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gemini",
				releaseDate: "2026-04-14",
			},
			"gemma-4-26b-a4b-it": {
				model: {
					id: "gemma-4-26b-a4b-it",
					name: "Gemma 4 26B A4B IT",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 262144,
					maxTokens: 32768,
				},
				family: "gemma",
				releaseDate: "2026-04-02",
			},
			"gemini-embedding-001": {
				model: {
					id: "gemini-embedding-001",
					name: "Gemini Embedding 001",
					reasoning: false,
					input: ["text"],
					contextWindow: 2048,
					maxTokens: 1,
					cost: {
						input: 0.15,
						output: 0,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gemini",
				releaseDate: "2025-05-20",
			},
			"gemini-2.0-flash": {
				model: {
					id: "gemini-2.0-flash",
					name: "Gemini 2.0 Flash",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 8192,
					cost: {
						input: 0.1,
						output: 0.4,
						cacheRead: 0.025,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash",
				releaseDate: "2024-12-11",
			},
			"gemini-3.6-flash": {
				model: {
					id: "gemini-3.6-flash",
					name: "Gemini 3.6 Flash",
					reasoning: true,
					reasoningLevels: ["minimal", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 1.5,
						output: 7.5,
						cacheRead: 0.15,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash",
				releaseDate: "2026-07-21",
			},
			"gemini-3.1-flash-lite": {
				model: {
					id: "gemini-3.1-flash-lite",
					name: "Gemini 3.1 Flash Lite",
					reasoning: true,
					reasoningLevels: ["minimal", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 0.25,
						output: 1.5,
						cacheRead: 0.025,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash-lite",
				releaseDate: "2026-05-07",
			},
			"gemma-4-31b-it": {
				model: {
					id: "gemma-4-31b-it",
					name: "Gemma 4 31B IT",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 262144,
					maxTokens: 32768,
				},
				family: "gemma",
				releaseDate: "2026-04-02",
			},
			"gemini-3.1-flash-image": {
				model: {
					id: "gemini-3.1-flash-image",
					name: "Nano Banana 2",
					reasoning: true,
					reasoningLevels: ["minimal", "high"],
					input: ["text", "image"],
					contextWindow: 65536,
					maxTokens: 65536,
					cost: {
						input: 0.5,
						output: 60,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash",
				releaseDate: "2026-05-28",
			},
			"gemini-2.5-flash-image": {
				model: {
					id: "gemini-2.5-flash-image",
					name: "Nano Banana",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 32768,
					maxTokens: 32768,
					cost: {
						input: 0.3,
						output: 30,
						cacheRead: 0.075,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash",
				releaseDate: "2025-08-26",
			},
			"gemini-3-pro-image": {
				model: {
					id: "gemini-3-pro-image",
					name: "Nano Banana Pro",
					reasoning: true,
					reasoningLevels: ["low", "high"],
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 32768,
					cost: {
						input: 2,
						output: 120,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gemini-pro",
				releaseDate: "2026-05-28",
			},
			"gemini-3.1-pro-preview": {
				model: {
					id: "gemini-3.1-pro-preview",
					name: "Gemini 3.1 Pro Preview",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 2,
						output: 12,
						cacheRead: 0.2,
						cacheWrite: 0,
					},
				},
				family: "gemini-pro",
				releaseDate: "2026-02-19",
			},
			"gemini-flash-lite-latest": {
				model: {
					id: "gemini-flash-lite-latest",
					name: "Gemini Flash-Lite Latest",
					reasoning: true,
					reasoningLevels: ["minimal", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 0.25,
						output: 1.5,
						cacheRead: 0.025,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash-lite",
				releaseDate: "2026-05-07",
			},
			"gemini-2.5-pro": {
				model: {
					id: "gemini-2.5-pro",
					name: "Gemini 2.5 Pro",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 1.25,
						output: 10,
						cacheRead: 0.125,
						cacheWrite: 0,
					},
				},
				family: "gemini-pro",
				releaseDate: "2025-06-17",
			},
			"gemini-3-pro-preview": {
				model: {
					id: "gemini-3-pro-preview",
					name: "Gemini 3 Pro Preview",
					reasoning: true,
					reasoningLevels: ["low", "high"],
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 2,
						output: 12,
						cacheRead: 0.2,
						cacheWrite: 0,
					},
				},
				family: "gemini-pro",
				releaseDate: "2025-11-18",
			},
			"gemini-2.5-flash-lite": {
				model: {
					id: "gemini-2.5-flash-lite",
					name: "Gemini 2.5 Flash-Lite",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 0.1,
						output: 0.4,
						cacheRead: 0.01,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash-lite",
				releaseDate: "2025-06-17",
			},
			"gemini-2.0-flash-lite": {
				model: {
					id: "gemini-2.0-flash-lite",
					name: "Gemini 2.0 Flash-Lite",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 1048576,
					maxTokens: 8192,
					cost: {
						input: 0.075,
						output: 0.3,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash-lite",
				releaseDate: "2024-12-11",
			},
			"gemini-3.1-flash-live-preview": {
				model: {
					id: "gemini-3.1-flash-live-preview",
					name: "Gemini 3.1 Flash Live Preview",
					reasoning: true,
					reasoningLevels: ["minimal", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 65536,
					cost: {
						input: 0.75,
						output: 4.5,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "gemini-flash",
				releaseDate: "2026-03-26",
			},
		},
		grok: {
			"grok-4.3": {
				model: {
					id: "grok-4.3",
					name: "Grok 4.3",
					reasoning: true,
					reasoningLevels: ["none", "low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 30000,
					cost: {
						input: 1.25,
						output: 2.5,
						cacheRead: 0.2,
						cacheWrite: 0,
					},
				},
				family: "grok",
				releaseDate: "2026-04-17",
			},
			"grok-4.20-0309-non-reasoning": {
				model: {
					id: "grok-4.20-0309-non-reasoning",
					name: "Grok 4.20 (Non-Reasoning)",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 30000,
					cost: {
						input: 1.25,
						output: 2.5,
						cacheRead: 0.2,
						cacheWrite: 0,
					},
				},
				family: "grok",
				releaseDate: "2026-03-09",
			},
			"grok-4.20-multi-agent-0309": {
				model: {
					id: "grok-4.20-multi-agent-0309",
					name: "Grok 4.20 Multi-Agent",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high", "xhigh"],
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 30000,
					cost: {
						input: 1.25,
						output: 2.5,
						cacheRead: 0.2,
						cacheWrite: 0,
					},
				},
				family: "grok",
				releaseDate: "2026-03-09",
			},
			"grok-4.5": {
				model: {
					id: "grok-4.5",
					name: "Grok 4.5",
					reasoning: true,
					reasoningLevels: ["low", "medium", "high"],
					input: ["text", "image"],
					contextWindow: 500000,
					maxTokens: 500000,
					cost: {
						input: 2,
						output: 6,
						cacheRead: 0.3,
						cacheWrite: 0,
					},
				},
				family: "grok",
				releaseDate: "2026-07-08",
			},
			"grok-build-0.1": {
				model: {
					id: "grok-build-0.1",
					name: "Grok Build 0.1",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 256000,
					maxTokens: 256000,
					cost: {
						input: 1,
						output: 2,
						cacheRead: 0.2,
						cacheWrite: 0,
					},
				},
				family: "grok-build",
				releaseDate: "2026-04-16",
			},
			"grok-4.20-0309-reasoning": {
				model: {
					id: "grok-4.20-0309-reasoning",
					name: "Grok 4.20 (Reasoning)",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 30000,
					cost: {
						input: 1.25,
						output: 2.5,
						cacheRead: 0.2,
						cacheWrite: 0,
					},
				},
				family: "grok",
				releaseDate: "2026-03-09",
			},
		},
		qwen: {
			"qwen3-coder-480b-a35b-instruct": {
				model: {
					id: "qwen3-coder-480b-a35b-instruct",
					name: "Qwen3-Coder 480B-A35B Instruct",
					reasoning: false,
					input: ["text"],
					contextWindow: 262144,
					maxTokens: 65536,
					cost: {
						input: 1.5,
						output: 7.5,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-04-01",
			},
			"qwen3.7-plus": {
				model: {
					id: "qwen3.7-plus",
					name: "Qwen3.7 Plus",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 65536,
					cost: {
						input: 0.5,
						output: 3,
						cacheRead: 0.05,
						cacheWrite: 0.625,
					},
				},
				family: "qwen",
				releaseDate: "2026-06-02",
			},
			"qwen3-vl-plus": {
				model: {
					id: "qwen3-vl-plus",
					name: "Qwen3-VL Plus",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 262144,
					maxTokens: 32768,
					cost: {
						input: 0.2,
						output: 1.6,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-09-23",
			},
			"qwen3-32b": {
				model: {
					id: "qwen3-32b",
					name: "Qwen3 32B",
					reasoning: true,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 16384,
					cost: {
						input: 0.7,
						output: 2.8,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-04-01",
			},
			"qwen3.6-35b-a3b": {
				model: {
					id: "qwen3.6-35b-a3b",
					name: "Qwen3.6 35B-A3B",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 262144,
					maxTokens: 65536,
					cost: {
						input: 0.248,
						output: 1.485,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2026-04-17",
			},
			"qwen-mt-plus": {
				model: {
					id: "qwen-mt-plus",
					name: "Qwen-MT Plus",
					reasoning: false,
					input: ["text"],
					contextWindow: 16384,
					maxTokens: 8192,
					cost: {
						input: 2.46,
						output: 7.37,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-01-01",
			},
			"qwen2-5-vl-72b-instruct": {
				model: {
					id: "qwen2-5-vl-72b-instruct",
					name: "Qwen2.5-VL 72B Instruct",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 8192,
					cost: {
						input: 2.8,
						output: 8.4,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-09-01",
			},
			"qwen-max": {
				model: {
					id: "qwen-max",
					name: "Qwen Max",
					reasoning: false,
					input: ["text"],
					contextWindow: 32768,
					maxTokens: 8192,
					cost: {
						input: 1.6,
						output: 6.4,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-04-03",
			},
			"qwen3.5-plus": {
				model: {
					id: "qwen3.5-plus",
					name: "Qwen3.5 Plus",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 65536,
					cost: {
						input: 0.4,
						output: 2.4,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2026-02-16",
			},
			"qwen-omni-turbo": {
				model: {
					id: "qwen-omni-turbo",
					name: "Qwen-Omni Turbo",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 32768,
					maxTokens: 2048,
					cost: {
						input: 0.07,
						output: 0.27,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-01-19",
			},
			"qwen-vl-max": {
				model: {
					id: "qwen-vl-max",
					name: "Qwen-VL Max",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 8192,
					cost: {
						input: 0.8,
						output: 3.2,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-04-08",
			},
			"qwen3-coder-30b-a3b-instruct": {
				model: {
					id: "qwen3-coder-30b-a3b-instruct",
					name: "Qwen3-Coder 30B-A3B Instruct",
					reasoning: false,
					input: ["text"],
					contextWindow: 262144,
					maxTokens: 65536,
					cost: {
						input: 0.45,
						output: 2.25,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-04-01",
			},
			"qwen3.5-27b": {
				model: {
					id: "qwen3.5-27b",
					name: "Qwen3.5 27B",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 262144,
					maxTokens: 65536,
					cost: {
						input: 0.3,
						output: 2.4,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2026-02-23",
			},
			"qwen3-vl-235b-a22b": {
				model: {
					id: "qwen3-vl-235b-a22b",
					name: "Qwen3-VL 235B-A22B",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 32768,
					cost: {
						input: 0.7,
						output: 2.8,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-04-01",
			},
			"qwen2-5-72b-instruct": {
				model: {
					id: "qwen2-5-72b-instruct",
					name: "Qwen2.5 72B Instruct",
					reasoning: false,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 8192,
					cost: {
						input: 1.4,
						output: 5.6,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-09-01",
			},
			"qwen3.7-max": {
				model: {
					id: "qwen3.7-max",
					name: "Qwen3.7 Max",
					reasoning: true,
					input: ["text"],
					contextWindow: 1000000,
					maxTokens: 65536,
					cost: {
						input: 2.5,
						output: 7.5,
						cacheRead: 0.5,
						cacheWrite: 3.125,
					},
				},
				family: "qwen",
				releaseDate: "2026-05-21",
			},
			"qwen3-next-80b-a3b-thinking": {
				model: {
					id: "qwen3-next-80b-a3b-thinking",
					name: "Qwen3-Next 80B-A3B (Thinking)",
					reasoning: true,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 32768,
					cost: {
						input: 0.5,
						output: 6,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-09-01",
			},
			"qwen-mt-turbo": {
				model: {
					id: "qwen-mt-turbo",
					name: "Qwen-MT Turbo",
					reasoning: false,
					input: ["text"],
					contextWindow: 16384,
					maxTokens: 8192,
					cost: {
						input: 0.16,
						output: 0.49,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-01-01",
			},
			"qvq-max": {
				model: {
					id: "qvq-max",
					name: "QVQ Max",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 8192,
					cost: {
						input: 1.2,
						output: 4.8,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qvq",
				releaseDate: "2025-03-25",
			},
			"qwen2-5-vl-7b-instruct": {
				model: {
					id: "qwen2-5-vl-7b-instruct",
					name: "Qwen2.5-VL 7B Instruct",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 8192,
					cost: {
						input: 0.35,
						output: 1.05,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-09-01",
			},
			"qwen3.6-27b": {
				model: {
					id: "qwen3.6-27b",
					name: "Qwen3.6 27B",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 262144,
					maxTokens: 65536,
					cost: {
						input: 0.6,
						output: 3.6,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2026-04-22",
			},
			"qwen3.5-35b-a3b": {
				model: {
					id: "qwen3.5-35b-a3b",
					name: "Qwen3.5 35B-A3B",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 262144,
					maxTokens: 65536,
					cost: {
						input: 0.25,
						output: 2,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2026-02-23",
			},
			"qwen3-vl-30b-a3b": {
				model: {
					id: "qwen3-vl-30b-a3b",
					name: "Qwen3-VL 30B-A3B",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 32768,
					cost: {
						input: 0.2,
						output: 0.8,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-04-01",
			},
			"qwen3-14b": {
				model: {
					id: "qwen3-14b",
					name: "Qwen3 14B",
					reasoning: true,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 8192,
					cost: {
						input: 0.35,
						output: 1.4,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-04-01",
			},
			"qwen2-5-32b-instruct": {
				model: {
					id: "qwen2-5-32b-instruct",
					name: "Qwen2.5 32B Instruct",
					reasoning: false,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 8192,
					cost: {
						input: 0.7,
						output: 2.8,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-09-01",
			},
			"qwen3-omni-flash-realtime": {
				model: {
					id: "qwen3-omni-flash-realtime",
					name: "Qwen3-Omni Flash Realtime",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 65536,
					maxTokens: 16384,
					cost: {
						input: 0.52,
						output: 1.99,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-09-15",
			},
			"qwen3-235b-a22b": {
				model: {
					id: "qwen3-235b-a22b",
					name: "Qwen3 235B-A22B",
					reasoning: true,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 16384,
					cost: {
						input: 0.7,
						output: 2.8,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-04-01",
			},
			"qwen3-max": {
				model: {
					id: "qwen3-max",
					name: "Qwen3 Max",
					reasoning: false,
					input: ["text"],
					contextWindow: 262144,
					maxTokens: 65536,
					cost: {
						input: 1.2,
						output: 6,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-09-23",
			},
			"qwen3-8b": {
				model: {
					id: "qwen3-8b",
					name: "Qwen3 8B",
					reasoning: true,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 8192,
					cost: {
						input: 0.18,
						output: 0.7,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-04-01",
			},
			"qwen2-5-14b-instruct": {
				model: {
					id: "qwen2-5-14b-instruct",
					name: "Qwen2.5 14B Instruct",
					reasoning: false,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 8192,
					cost: {
						input: 0.35,
						output: 1.4,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-09-01",
			},
			"qwen3-coder-plus": {
				model: {
					id: "qwen3-coder-plus",
					name: "Qwen3 Coder Plus",
					reasoning: false,
					input: ["text"],
					contextWindow: 1048576,
					maxTokens: 65536,
					cost: {
						input: 1,
						output: 5,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-07-23",
			},
			"qwen2-5-7b-instruct": {
				model: {
					id: "qwen2-5-7b-instruct",
					name: "Qwen2.5 7B Instruct",
					reasoning: false,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 8192,
					cost: {
						input: 0.175,
						output: 0.7,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-09-01",
			},
			"qwen3-coder-flash": {
				model: {
					id: "qwen3-coder-flash",
					name: "Qwen3 Coder Flash",
					reasoning: false,
					input: ["text"],
					contextWindow: 1000000,
					maxTokens: 65536,
					cost: {
						input: 0.3,
						output: 1.5,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-07-28",
			},
			"qwen-flash": {
				model: {
					id: "qwen-flash",
					name: "Qwen Flash",
					reasoning: true,
					input: ["text"],
					contextWindow: 1000000,
					maxTokens: 32768,
					cost: {
						input: 0.05,
						output: 0.4,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-07-28",
			},
			"qwen-plus": {
				model: {
					id: "qwen-plus",
					name: "Qwen Plus",
					reasoning: true,
					input: ["text"],
					contextWindow: 1000000,
					maxTokens: 32768,
					cost: {
						input: 0.4,
						output: 1.2,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-01-25",
			},
			"qwen-omni-turbo-realtime": {
				model: {
					id: "qwen-omni-turbo-realtime",
					name: "Qwen-Omni Turbo Realtime",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 32768,
					maxTokens: 2048,
					cost: {
						input: 0.27,
						output: 1.07,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-05-08",
			},
			"qwen-turbo": {
				model: {
					id: "qwen-turbo",
					name: "Qwen Turbo",
					reasoning: true,
					input: ["text"],
					contextWindow: 1000000,
					maxTokens: 16384,
					cost: {
						input: 0.05,
						output: 0.2,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-11-01",
			},
			"qwen2-5-omni-7b": {
				model: {
					id: "qwen2-5-omni-7b",
					name: "Qwen2.5-Omni 7B",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 32768,
					maxTokens: 2048,
					cost: {
						input: 0.1,
						output: 0.4,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-12-01",
			},
			"qwen3-asr-flash": {
				model: {
					id: "qwen3-asr-flash",
					name: "Qwen3-ASR Flash",
					reasoning: false,
					contextWindow: 53248,
					maxTokens: 4096,
					cost: {
						input: 0.035,
						output: 0.035,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-09-08",
			},
			"qwq-plus": {
				model: {
					id: "qwq-plus",
					name: "QwQ Plus",
					reasoning: true,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 8192,
					cost: {
						input: 0.8,
						output: 2.4,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-03-05",
			},
			"qwen3.6-flash": {
				model: {
					id: "qwen3.6-flash",
					name: "Qwen3.6 Flash",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 65536,
					cost: {
						input: 0.1875,
						output: 1.125,
						cacheRead: 0,
						cacheWrite: 0.234375,
					},
				},
				family: "qwen3.6",
				releaseDate: "2026-04-27",
			},
			"qwen3.5-397b-a17b": {
				model: {
					id: "qwen3.5-397b-a17b",
					name: "Qwen3.5 397B-A17B",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 262144,
					maxTokens: 65536,
					cost: {
						input: 0.6,
						output: 3.6,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2026-02-15",
			},
			"qwen3.6-max-preview": {
				model: {
					id: "qwen3.6-max-preview",
					name: "Qwen3.6 Max Preview",
					reasoning: true,
					input: ["text"],
					contextWindow: 262144,
					maxTokens: 65536,
					cost: {
						input: 1.3,
						output: 7.8,
						cacheRead: 0.13,
						cacheWrite: 1.625,
					},
				},
				family: "qwen",
				releaseDate: "2026-04-20",
			},
			"qwen-vl-ocr": {
				model: {
					id: "qwen-vl-ocr",
					name: "Qwen-VL OCR",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 34096,
					maxTokens: 4096,
					cost: {
						input: 0.72,
						output: 0.72,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-10-28",
			},
			"qwen3-livetranslate-flash-realtime": {
				model: {
					id: "qwen3-livetranslate-flash-realtime",
					name: "Qwen3-LiveTranslate Flash Realtime",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 53248,
					maxTokens: 4096,
					cost: {
						input: 10,
						output: 10,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-09-22",
			},
			"qwen-plus-character-ja": {
				model: {
					id: "qwen-plus-character-ja",
					name: "Qwen Plus Character (Japanese)",
					reasoning: false,
					input: ["text"],
					contextWindow: 8192,
					maxTokens: 512,
					cost: {
						input: 0.5,
						output: 1.4,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-01-01",
			},
			"qwen3-omni-flash": {
				model: {
					id: "qwen3-omni-flash",
					name: "Qwen3-Omni Flash",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 65536,
					maxTokens: 16384,
					cost: {
						input: 0.43,
						output: 1.66,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-09-15",
			},
			"qwen3.6-plus": {
				model: {
					id: "qwen3.6-plus",
					name: "Qwen3.6 Plus",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 1000000,
					maxTokens: 65536,
					cost: {
						input: 0.5,
						output: 3,
						cacheRead: 0.05,
						cacheWrite: 0.625,
					},
				},
				family: "qwen",
				releaseDate: "2026-04-02",
			},
			"qwen3.5-122b-a10b": {
				model: {
					id: "qwen3.5-122b-a10b",
					name: "Qwen3.5 122B-A10B",
					reasoning: true,
					input: ["text", "image"],
					contextWindow: 262144,
					maxTokens: 65536,
					cost: {
						input: 0.4,
						output: 3.2,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2026-02-23",
			},
			"qwen3-next-80b-a3b-instruct": {
				model: {
					id: "qwen3-next-80b-a3b-instruct",
					name: "Qwen3-Next 80B-A3B Instruct",
					reasoning: false,
					input: ["text"],
					contextWindow: 131072,
					maxTokens: 32768,
					cost: {
						input: 0.5,
						output: 2,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2025-09-01",
			},
			"qwen-vl-plus": {
				model: {
					id: "qwen-vl-plus",
					name: "Qwen-VL Plus",
					reasoning: false,
					input: ["text", "image"],
					contextWindow: 131072,
					maxTokens: 8192,
					cost: {
						input: 0.21,
						output: 0.63,
						cacheRead: 0,
						cacheWrite: 0,
					},
				},
				family: "qwen",
				releaseDate: "2024-01-25",
			},
		},
	},
};
